#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Rasterize the same symbolic SVGs used by LumaUI's native window controls.

Build-only GdkPixbuf/librsvg input, no hand-drawn substitute control geometry.
Lucide ISC attribution remains with the icon theme and its upstream sources.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "src/luma-platform/compat/luma-frame-glyphs.h"


def render():
    import gi
    gi.require_version("GdkPixbuf", "2.0")
    from gi.repository import GdkPixbuf
    size = json.loads((ROOT / "config/shared/design-tokens.json").read_text())["lumaui"]["window"]["control_icon"]
    license_path = ROOT / "assets/icon-theme/Prairie/upstream/lucide/lumaui/LICENSE.txt"
    license_notice = "/* SPDX-License-Identifier: ISC AND MIT\n" + "\n".join(
        (" * " + line).rstrip() for line in license_path.read_text().splitlines()) + "\n */"
    lines = [license_notice, "/* Generated by scripts/developer/generate-luma-frame-glyphs.py.",
             " * Lucide symbolic geometry, ISC; see assets/icon-theme/Prairie/upstream/lucide/lumaui/LICENSE.txt.",
             " * Exact native LumaUI control SVGs, rasterized at the shared control_icon size. */",
             "#pragma once", "#include <stdint.h>", f"#define LUMA_FRAME_GLYPH_SIZE {size}"]
    for role, name in (("minimize", "minus"), ("maximize", "maximize-2"),
                       ("restore", "minimize-2"), ("close", "x"), ("back", "chevron-left")):
        path = ROOT / f"assets/icon-theme/Prairie/symbolic/actions/lumaui-{name}-symbolic.svg"
        pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(str(path), size, size, False)
        if not pixbuf.get_has_alpha() or (pixbuf.get_width(), pixbuf.get_height()) != (size, size):
            raise ValueError(f"Invalid native symbolic control raster: {path}")
        pixels, stride, channels = pixbuf.get_pixels(), pixbuf.get_rowstride(), pixbuf.get_n_channels()
        alpha = [pixels[y * stride + x * channels + channels - 1]
                 for y in range(size) for x in range(size)]
        if not any(alpha):
            raise ValueError(f"Empty native control raster: {path}")
        lines += [f"/* {path.relative_to(ROOT)} SHA256 {hashlib.sha256(path.read_bytes()).hexdigest()} */",
                  f"static const uint8_t luma_frame_{role}_glyph[{size * size}] = {{"]
        lines += ["    " + ",".join(map(str, alpha[y * size:(y + 1) * size])) + "," for y in range(size)]
        lines += ["};"]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    options = parser.parse_args()
    text = render()
    if options.check:
        if options.output.read_text() != text:
            sys.exit("Compatibility control glyphs differ from native LumaUI SVGs; regenerate them.")
    else:
        options.output.write_text(text)
