#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0
"""Render a Luma runtime container.yaml from Fedora's definition and a Luma overlay.

Fedora maintains the package closure, extension points, environment and cleanup
commands of its Flatpak runtime in flatpaks/flatpak-runtime. Luma builds its
runtime from the same Fedora 44 packages, so it starts from a pinned copy of
that file (packaging/flatpak/runtime/fedora-f44/) and applies a small, reviewed
overlay: Luma ids, Luma's own packages, and the few cleanup changes Luma makes.
Keeping the overlay separate keeps every divergence from Fedora visible and makes
rebasing onto a newer Fedora definition a copy plus a diff review.

Overlay keys (all optional except base and flatpak):

  base                 path of the Fedora container.yaml, relative to the overlay;
                       omitted for components Fedora does not build (Office)
  flatpak              keys that replace Fedora's (id, sdk, runtime, branch, ...)
  rename               ordered mapping of id prefixes to rewrite everywhere
  drop-extensions      extension names (after renaming) to remove
  extension-overrides  per-extension keys to set (after renaming)
  add-packages         packages appended to Fedora's list
  remove-packages      packages removed from Fedora's list
  cleanup-replace      list of {from, to} exact text replacements in cleanup-commands
  cleanup-append       text appended to cleanup-commands
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


class LiteralString(str):
    pass


def _literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


yaml.SafeDumper.add_representer(LiteralString, _literal_representer)


def _rename(value: str, rename: dict[str, str]) -> str:
    for old, new in rename.items():
        value = value.replace(old, new)
    return value


def render(overlay_path: Path) -> dict:
    overlay = yaml.safe_load(overlay_path.read_text())
    if overlay.get("base"):
        base_path = (overlay_path.parent / overlay["base"]).resolve()
        base = yaml.safe_load(base_path.read_text())
    else:
        base = {"flatpak": {}}
    flatpak = dict(base["flatpak"])
    rename = overlay.get("rename", {})

    extensions = {}
    for name, ext in (flatpak.get("add-extensions") or {}).items():
        new_name = _rename(name, rename)
        new_ext = {k: (_rename(v, rename) if isinstance(v, str) else v) for k, v in ext.items()}
        extensions[new_name] = new_ext
    for name in overlay.get("drop-extensions", []):
        if name not in extensions:
            raise SystemExit(f"drop-extensions: {name} is not declared by the base")
        del extensions[name]
    for name, keys in (overlay.get("extension-overrides") or {}).items():
        extensions.setdefault(name, {}).update(keys)
    if extensions:
        flatpak["add-extensions"] = extensions

    if "finish-args" in flatpak:
        flatpak["finish-args"] = _rename(flatpak["finish-args"], rename)

    cleanup = flatpak.get("cleanup-commands", "")
    cleanup = _rename(cleanup, rename)
    for item in overlay.get("cleanup-replace") or []:
        if item["from"] not in cleanup:
            raise SystemExit(f"cleanup-replace: text not found in base cleanup: {item['from'][:60]!r}")
        cleanup = cleanup.replace(item["from"], item["to"])
    if overlay.get("cleanup-append"):
        cleanup = cleanup.rstrip("\n") + "\n\n" + overlay["cleanup-append"].rstrip("\n") + "\n"
    if cleanup:
        flatpak["cleanup-commands"] = LiteralString(cleanup)

    packages = list(flatpak.get("packages", []))
    remove = set(overlay.get("remove-packages", []))
    names = {p if isinstance(p, str) else p["name"] for p in packages}
    missing = remove - names
    if missing:
        raise SystemExit(f"remove-packages: not in base: {sorted(missing)}")
    packages = [p for p in packages if (p if isinstance(p, str) else p["name"]) not in remove]
    for package in overlay.get("add-packages", []):
        if package in names:
            raise SystemExit(f"add-packages: {package} is already in the base list")
        packages.append(package)
    flatpak["packages"] = packages

    for key, value in overlay["flatpak"].items():
        flatpak[key] = value

    return {"flatpak": flatpak}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("overlay", type=Path)
    parser.add_argument("-o", "--output", type=Path)
    args = parser.parse_args()
    document = render(args.overlay)
    text = ("# Generated by scripts/depot/runtime/generate-container-yaml.py from\n"
            f"# {args.overlay.name}. Do not edit; edit the overlay.\n")
    text += yaml.safe_dump(document, sort_keys=False, width=100, allow_unicode=True)
    if args.output:
        args.output.write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
