#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
build_script="$repo_root/scripts/mobile/build-luma-shell-fp6.sh"
handheld_fp6_build="$repo_root/scripts/mobile/build-luma-handheld-fp6.sh"
keyboard_lab_build="$repo_root/scripts/mobile/build-keyboard-labs-fp6.sh"
keyboard_runtime_build="$repo_root/scripts/mobile/build-luma-keyboard-fp6.sh"
stevia_runtime_build="$repo_root/scripts/mobile/build-luma-stevia-fp6.sh"
stevia_patch="$repo_root/patches/stevia/0001-luma-latinime-completer.patch"
stevia_visual_patch="$repo_root/patches/stevia/0002-luma-compact-dark-keyboard.patch"
phosh_patch="$repo_root/patches/phosh/0001-luma-handheld-home-dock-search.patch"
phosh_parity_patch="$repo_root/patches/phosh/0002-luma-status-order-search-purpose.patch"
phosh_lock_motion_patch="$repo_root/patches/phosh/0017-luma-physical-lock-carousel.patch"
phosh_drawer_owner_patch="$repo_root/patches/phosh/0018-luma-single-owner-touch-drawers.patch"
phoc_drawer_patch="$repo_root/patches/phoc/0007-luma-physical-drawer-settling.patch"
lomiri_keyboard_build="$repo_root/scripts/mobile/build-lomiri-keyboard-lab-fp6.sh"
lomiri_runtime_packager="$repo_root/scripts/mobile/package-lomiri-keyboard-runtime-fp6.sh"
adr="$repo_root/docs/decisions/007-converged-adaptive-luma-shell.md"
handheld_extension="$repo_root/extensions/luma-handheld/extension.js"
handheld_metadata="$repo_root/extensions/luma-handheld/metadata.json"
handheld_stylesheet="$repo_root/extensions/luma-handheld/handheld.css"
power_broker="$repo_root/extensions/luma-handheld/luma-power-key-broker.py"
power_broker_service="$repo_root/extensions/luma-handheld/luma-power-key-broker.service"
power_rule="$repo_root/extensions/luma-handheld/70-luma-handheld-power-key.rules"
display_power_acceptance="$repo_root/scripts/mobile/accept-fp6-display-power.sh"
input_settings="$repo_root/extensions/luma-handheld/luma-mobile-input-settings.py"
handheld_schema="$repo_root/extensions/luma-handheld/org.project_luma.handheld.gschema.xml"
keyboard_lab="$repo_root/extensions/luma-handheld/luma-keyboard-lab"
keyboard_lab_session="$repo_root/extensions/luma-handheld/luma-keyboard-lab-session"
keyboard_lab_entry="$repo_root/extensions/luma-handheld/luma-keyboard-lab-entry.py"
kwin_keyboard_engine="$repo_root/extensions/luma-handheld/luma-kwin-keyboard-engine"
wkeys_direct_session="$repo_root/scripts/mobile/luma-wkeys-direct-session"
wkeys_direct_client="$repo_root/scripts/mobile/luma-wkeys-direct-client"
lomiri_direct_session="$repo_root/scripts/mobile/luma-lomiri-direct-session"
wkeys_layout="$repo_root/extensions/luma-handheld/wkeys-mobile-layout.toml"
wkeys_style="$repo_root/extensions/luma-handheld/wkeys-mobile-style.css"
handheld_profile="$repo_root/config/mobile/luma-shell-handheld.dconf"
latinime_engine="$repo_root/src/luma-keyboard/luma_ibus_engine.py"
latinime_component="$repo_root/src/luma-keyboard/luma-latinime.xml"

bash -n "$build_script"
bash -n "$keyboard_lab_build"
bash -n "$keyboard_runtime_build"
bash -n "$stevia_runtime_build"
bash -n "$lomiri_keyboard_build"
bash -n "$lomiri_runtime_packager"
bash -n "$repo_root/scripts/packages/build-luma-handheld.sh"
bash -n "$handheld_fp6_build"
bash -n "$display_power_acceptance"
grep -Fq '$(uname -m)" != aarch64' "$build_script"
grep -Fq 'GNOME_SHELL_SRPM_SHA256' "$build_script"
grep -Fq 'screen-keyboard-enabled' "$build_script"
grep -Fq 'NATIVE_OSK_PRESENT=true' "$build_script"
grep -Fq 'STEVIA_RESCUE_REQUIRED=true' "$build_script"
grep -Fq '0008-luma-handheld-activity-view.patch' "$build_script"
grep -Fq 'HANDHELD_CARD_STEP_RATIO' \
  "$repo_root/patches/gnome-shell/0008-luma-handheld-activity-view.patch"
grep -Fq 'get_accumulated_delta()' \
  "$repo_root/patches/gnome-shell/0008-luma-handheld-activity-view.patch"
grep -Fq 'selected?.requestClose()' \
  "$repo_root/patches/gnome-shell/0008-luma-handheld-activity-view.patch"
grep -Fq 'startGesture.set_enabled(!handheldMode)' \
  "$repo_root/patches/gnome-shell/0008-luma-handheld-activity-view.patch"
grep -Fq 'HANDHELD_ACTIVITY_VIEW_USES_DESKTOP_CHROME' \
  "$repo_root/patches/gnome-shell/0008-luma-handheld-activity-view.patch"
grep -Fq 'SQUEEKBOARD_LAB_RPM_SHA256' "$keyboard_lab_build"
grep -Fq 'LATINIME_UPSTREAM_COMMIT' "$keyboard_runtime_build"
grep -Fq 'aarch64-linux-musl' "$keyboard_runtime_build"
grep -Fq 'SECOND_COMPOSITOR_REQUIRED=false' "$keyboard_runtime_build"
grep -Fq '0001-luma-latinime-completer.patch' "$stevia_runtime_build"
grep -Fq 'test-completer-luma' "$stevia_runtime_build"
grep -Fq 'QT_REQUIRED=false' "$stevia_runtime_build"
grep -Fq 'LUMA_MIN_AUTOCORRECT_SCORE' "$stevia_patch"
grep -Fq 'LUMA_MIN_AUTOCORRECT_MARGIN' "$stevia_patch"
grep -Fq 'LUMA_MIN_COMPOUND_SCORE' "$stevia_patch"
grep -Fq 'LUMA_MIN_COMPOUND_MARGIN' "$stevia_patch"
grep -Fq 'exact_match = TRUE' "$stevia_patch"
grep -Fq '"if", "bath", "pour", "crash"' "$stevia_patch"
grep -Fq '"andbsee", "and see "' "$stevia_patch"
grep -Fq '"tyojng", "typing "' "$stevia_patch"
grep -Fq '"whenbi", "when I "' "$stevia_patch"
grep -Fq '"itnfeelsnokah"' "$stevia_patch"
grep -Fq '"socool"' "$stevia_patch"
grep -Fq 'leaves-ambiguous-typo' "$stevia_patch"
grep -Fq 'style = "/mobi/phosh/stevia/stylesheet/adwaita-dark.css";' "$stevia_patch"
grep -Fq 'TARGET_PORTRAIT_PHYS_HEIGHT 30' "$stevia_visual_patch"
grep -Fq 'stylesheet/luma-dark.css' "$stevia_visual_patch"
grep -Fq 'app-grid-icon.c' "$phosh_patch"
grep -Fq 'LUMA_ICON_RADIUS 13.5' "$phosh_patch"
grep -Fq 'pixbuf_needs_canvas' "$phosh_patch"
grep -Fq 'full-size icons keep their own transparent rounded corners' "$phosh_patch"
grep -Fq 'search_background_tap' "$phosh_patch"
grep -Fq '<property name="has-frame">0</property>' "$phosh_patch"
grep -Fq '<property name="widget">PhoshTopPanel</property>' "$phosh_patch"
grep -Fq 'luma_tiling_setting' "$phosh_patch"
grep -Fq 'luma_location_setting' "$phosh_patch"
grep -Fq 'luma_warm_setting' "$phosh_patch"
grep -Fq '#define PHOSH_TOP_BAR_HEIGHT 48' "$phosh_patch"
grep -Fq 'gtk_widget_set_margin_top (self->box_clock, 0);' "$phosh_patch"
grep -Fq 'gtk_widget_class_bind_template_child (widget_class, PhoshQuickSettings, luma_tiling_setting);' "$phosh_patch"
grep -Fq '<object class="GtkGestureDrag" id="search_swipe">' "$phosh_patch"
grep -Fq '<signal name="drag-end" handler="on_search_swipe" swapped="true"/>' "$phosh_patch"
grep -Fq '<property name="name">luma-carrier-row</property>' "$phosh_patch"
grep -Fq 'id="percent_label"' "$phosh_patch"
grep -Fq '<class name="luma-section-separator"/>' "$phosh_patch"
grep -Fq '<property name="no-show-all">1</property>' "$phosh_patch"
grep -Fq 'id="search_placeholder"' "$phosh_patch"
grep -Fq '<property name="maximum-size">720</property>' "$phosh_patch"
grep -Fq 'PHOSH_TOP_PANEL_BG_MAX_OPACITY 1.0' "$phosh_patch"
grep -Fq '<property name="input-purpose">free-form</property>' "$phosh_parity_patch"
grep -Fq '<object class="GtkBox">' "$phosh_parity_patch"
grep -Fq '<property name="animation-duration">280</property>' "$phosh_lock_motion_patch"
grep -Fq -- '-  <object class="GtkGestureMultiPress" id="luma_unlock_tap">' \
  "$phosh_lock_motion_patch"
grep -Fq -- '-  <object class="GtkGestureSwipe" id="settings_swipe">' \
  "$phosh_drawer_owner_patch"
grep -Fq -- '-  <object class="GtkGestureSwipe" id="swipe_gesture">' \
  "$phosh_drawer_owner_patch"
grep -Fq -- '-  GtkGesture     *settings_swipe;' "$phosh_drawer_owner_patch"
grep -Fq -- '-    GtkGesture *swipe_gesture;' "$phosh_drawer_owner_patch"
grep -Fq '#define DRAG_ACCEPT_THRESHOLD_DISTANCE 8' "$phoc_drawer_patch"
grep -Fq '#define DRAG_SETTLE_V_MIN 650' "$phoc_drawer_patch"
grep -Fq 'parallel swipe recognizer' "$phoc_drawer_patch"
grep -Fq 'kwin plasma-keyboard maliit-keyboard' "$keyboard_lab_build"
grep -Fq 'podman export' "$keyboard_lab_build"
grep -Fq 'PHONE_ACCESSED=false' "$build_script"
grep -Fq 'PACKAGES_INSTALLED=false' "$build_script"
grep -Fq 'LUMA_FP6_HANDHELD_BUILD_VERSION=1' "$handheld_fp6_build"
grep -Fq 'PACKAGE_ARCHITECTURE=noarch' "$handheld_fp6_build"
grep -Fq '_reconcileEmptyActivityView()' "$handheld_fp6_build"
grep -Fq 'SESSION_STARTED=false' "$build_script"
grep -Fq 'Phosh/Phoc is retained as the FP6 hardware-bring-up and rescue session' "$adr"
grep -Fq 'handheld@project-luma.local' "$handheld_metadata"
grep -Fq 'handheld@project-luma.local' "$handheld_profile"
grep -Fq 'Main.overview.show();' "$handheld_extension"
! grep -Fq "Main.overview.showApps()" "$handheld_extension"
grep -Fq 'const MOBILE_LAUNCHER_COLUMNS = 4' "$handheld_extension"
grep -Fq 'const MOBILE_LAUNCHER_ICON_SIZE = 64' "$handheld_extension"
grep -Fq "name: 'lumaHandheldHome'" "$handheld_extension"
grep -Fq "name: 'lumaHandheldAppDrawer'" "$handheld_extension"
! grep -Fq "name: 'lumaHandheldAppSwitcher'" "$handheld_extension"
! grep -Fq 'new Shell.WindowPreviewLayout()' "$handheld_extension"
! grep -Fq 'paint_to_content' "$handheld_extension"
! grep -Fq 'pan_axis: Clutter.PanAxis.BOTH' "$handheld_extension"
! grep -Fq 'MOBILE_SWITCHER_' "$handheld_extension"
! grep -Fq '_handleMobileSwitcherTouch' "$handheld_extension"
grep -Fq '<method name="ShowAppSwitcher"/>' "$handheld_extension"
grep -Fq 'this._showWindowPicker();' "$handheld_extension"
grep -Fq 'this._bottomGesture = null' "$handheld_extension"
grep -Fq '_observeBottomNavigation(event)' "$handheld_extension"
grep -Fq 'const BOTTOM_GESTURE_DIRECTION_PX = 18' "$handheld_extension"
grep -Fq "this._recordGesture('bottomCandidates')" "$handheld_extension"
grep -Fq "this._recordGesture('bottomDirectionRejected')" "$handheld_extension"
! grep -Fq '_createBottomGesture()' "$handheld_extension"
grep -Fq 'this._finishBottomGesture(' "$handheld_extension"
! grep -Fq "this._bottomGesture.connect('progress'" "$handheld_extension"
grep -Fq 'vscrollbar_policy: St.PolicyType.AUTOMATIC' "$handheld_extension"
grep -Fq 'this._drawerPanGesture = new Clutter.PanGesture' "$handheld_extension"
grep -Fq '_updateDrawerPan(action)' "$handheld_extension"
grep -Fq 'this._hideAppDrawer(true, true)' "$handheld_extension"
grep -Fq 'this._mobileLaunchPendingApp = app' "$handheld_extension"
grep -Fq 'Meta.TabList.NORMAL_ALL' "$handheld_extension"
grep -Fq "this._mutterSettings.set_boolean('dynamic-workspaces', false)" "$handheld_extension"
grep -Fq "this._wmPreferences.set_int('num-workspaces', 1)" "$handheld_extension"
grep -Fq 'this._normalWorkspaceSwipeTracker.enabled = this._active' "$handheld_extension"
grep -Fq "this._actorHasStyleClass(source, 'show-apps')" "$handheld_extension"
grep -Fq '.luma-handheld .luma-handheld-home' "$handheld_stylesheet"
grep -Fq 'global.window_group.add_child(this._homeSurface)' \
  "$handheld_extension"
grep -Fq '_syncHomeStacking()' "$handheld_extension"
grep -Fq '_startActivityViewGuard()' "$handheld_extension"
! grep -Fq 'Clutter.EventPhase.CAPTURE' "$handheld_extension"
grep -Fq 'this._drawerReturnHome' "$handheld_extension"
grep -Fq '_bottomNavigationStartY(monitor)' "$handheld_extension"
grep -Fq 'event.get_coords()' "$handheld_extension"
grep -Fq '<method name="GetGestureDiagnostics">' "$handheld_extension"
grep -Fq '_recordGesture(name) {' "$handheld_extension"
! grep -Fq 'new Background.BackgroundManager' "$handheld_extension"
grep -Fq 'background-color: transparent' "$handheld_stylesheet"
grep -Fq '.luma-handheld .luma-handheld-app-drawer-sheet' "$handheld_stylesheet"
! grep -Fq '.luma-handheld .luma-handheld-switcher-card' "$handheld_stylesheet"
grep -Fq 'Meta.TabList.NORMAL' "$handheld_extension"
grep -Fq 'Clutter.KEY_Left' "$handheld_extension"
grep -Fq "appId.startsWith('waydroid.')" "$handheld_extension"
grep -Fq 'Clutter.KEY_Escape' "$handheld_extension"
grep -Fq '_showAndroidLaunchFailure(app)' "$handheld_extension"
grep -Fq 'fp6_kernel_admitted === false' "$handheld_extension"
grep -Fq 'prevent another system freeze' "$handheld_extension"
grep -Fq '.luma-handheld .luma-handheld-launch-detail' "$handheld_stylesheet"
grep -Fq 'monitor.height > monitor.width' "$handheld_extension"
grep -Fq "get_child('handheld.css')" "$handheld_extension"
grep -Fq '_bottomDragGesture' "$handheld_extension"
grep -Fq '_observeEdgeNavigation(event)' "$handheld_extension"
grep -Fq "this._recordGesture('edgeCandidates')" "$handheld_extension"
grep -Fq "this._recordGesture('edgeDirectionRejected')" "$handheld_extension"
! grep -Fq 'Shell.EdgeDragGesture' "$handheld_extension"
grep -Fq '_topSwipeAt(this._edgeTouchStartX)' "$handheld_extension"
grep -Fq 'new Clutter.PanGesture' "$handheld_extension"
grep -Fq 'dashtodockDashScrollview' "$handheld_extension"
grep -Fq 'scrollView.hadjustment.value -= delta.get_x()' "$handheld_extension"
grep -Fq 'padding: 0 0 14px 0' "$handheld_stylesheet"
grep -Fq 'this._dockContent.translation_y = this._active ? 5 : 0' "$handheld_extension"
grep -Fq "schema_id: 'org.gnome.shell.extensions.dash-to-dock'" "$handheld_extension"
grep -Fq 'const HOME_DOCK_FRACTION = 0.984' "$handheld_extension"
grep -Fq "this._dockSettings.set_double('height-fraction', fraction)" "$handheld_extension"
grep -Fq "this._dockSettings.set_boolean('extend-height', false)" "$handheld_extension"
grep -Fq "add_style_class_name('luma-handheld-app-open')" "$handheld_extension"
grep -Fq "name: 'lumaHandheldDockFill'" "$handheld_extension"
grep -Fq "findActorByStyleClass" "$handheld_extension"
grep -Fq 'this._dockBackground.get_transformed_position()' "$handheld_extension"
grep -Fq '.luma-handheld.luma-handheld-app-open #dashtodockContainer.bottom' "$handheld_stylesheet"
grep -Fq '.luma-handheld .luma-handheld-dock-fill' "$handheld_stylesheet"
grep -Fq 'border-radius: 0' "$handheld_stylesheet"
grep -Fq 'const APP_PICKER_HOLD_MS = 420' "$handheld_extension"
grep -Fq 'const BOTTOM_GESTURE_FALLBACK_PX = 104' "$handheld_extension"
grep -Fq '_beginBottomGesture(action)' "$handheld_extension"
grep -Fq '_goHome()' "$handheld_extension"
grep -Fq '_hasRunningApplication()' "$handheld_extension"
grep -Fq '_reconcileEmptyActivityView()' "$handheld_extension"
! grep -Fq 'this._bottomGestureAction.get_n_points() > 0' "$handheld_extension"
grep -Fq 'window.minimize()' "$handheld_extension"
grep -Fq "'captured-event', this._onCapturedEvent.bind(this)" "$handheld_extension"
grep -Fq 'Main.keyboard.open(Main.layoutManager.focusIndex)' "$handheld_extension"
grep -Fq 'sinceCollapseMs < 600' "$handheld_extension"
grep -Fq 'if (this._displaySleeping)' "$handheld_extension"
! grep -Fq 'Clutter.KEY_PowerOff' "$handheld_extension"
grep -Fq "Main.screenShield?.lock?.(true)" "$handheld_extension"
grep -Fq "'PowerSaveMode'" "$handheld_extension"
grep -Fq 'SleepDisplay()' "$handheld_extension"
grep -Fq 'WakeDisplay()' "$handheld_extension"
grep -Fq '_armIdleAfterWake()' "$handheld_extension"
grep -Fq 'this._idleRearmTimeoutId' "$handheld_extension"
grep -Fq 'org.project_luma.Handheld1' "$handheld_extension"
grep -Fq 'SetExternalKeyboardVisible' "$handheld_extension"
grep -Fq 'this._dockContainer.visible = !occluded' "$handheld_extension"
grep -Fq 'org.project_luma.Keyboard1' "$handheld_extension"
grep -Fq '_normalizeKeyboardTouch(event)' "$handheld_extension"
grep -Fq 'controller.commit(character, new Set())' "$handheld_extension"
grep -Fq 'Main.inputMethod.handleVirtualKey(keyval)' "$handheld_extension"
grep -Fq "this._lumaCandidateRow.show()" "$handheld_extension"
grep -Fq "'Compose'" "$handheld_extension"
grep -Fq "'Resolve'" "$handheld_extension"
grep -Fq "'SelectCandidate'" "$handheld_extension"
grep -Fq '_lumaPredictionAllowed(controller)' "$handheld_extension"
grep -Fq "style_class: 'luma-handheld-keyboard-navigation'" "$handheld_extension"
grep -Fq "icon_name: 'input-keyboard-symbolic'" "$handheld_extension"
grep -Fq "icon_name: 'pan-down-symbolic'" "$handheld_extension"
grep -Fq "iconName: 'osk-shift-symbolic'" "$handheld_extension"
grep -Fq "iconName: 'osk-delete-symbolic'" "$handheld_extension"
grep -Fq "iconName: 'osk-enter-symbolic'" "$handheld_extension"
grep -Fq "{label: '?123', action: 'numbers'" "$handheld_extension"
grep -Fq "{label: 'ABC', action: 'letters'" "$handheld_extension"
grep -Fq 'Math.max(404, typingHeight + navigationHeight)' "$handheld_extension"
grep -Fq 'this._lumaKeyboardSurface ??' "$handheld_extension"
grep -Fq '.luma-handheld .luma-handheld-keyboard-gesture-pill' "$handheld_stylesheet"
grep -Fq "<method name=\"Key\">" "$latinime_engine"
grep -Fq 'ACTIVE_ENGINE.forward_key_event' "$latinime_engine"
grep -Fq '<property name="ProcessKeyEvents"' "$latinime_engine"
grep -Fq '<property name="CandidateRefreshes"' "$latinime_engine"
grep -Fq '<property name="Autocorrections"' "$latinime_engine"
grep -Fq '<method name="Compose">' "$latinime_engine"
grep -Fq '<method name="Resolve">' "$latinime_engine"
grep -Fq '<method name="SelectCandidate">' "$latinime_engine"
grep -Fq '<property name="FallbackKeyEvents"' "$latinime_engine"
grep -Fq '<property name="FallbackResolutions"' "$latinime_engine"
grep -Fq "'luma-handheld-key-preview'" "$handheld_extension"
grep -Fq '.luma-handheld .luma-handheld-key-preview' "$handheld_stylesheet"
grep -Fq "Gio.DBus.session, '/org/project_luma/Handheld'" "$handheld_extension"
PYTHONPYCACHEPREFIX=${TMPDIR:-/tmp}/luma-python-cache \
  python3 -m py_compile "$power_broker"
grep -Fq 'pmic_pwrkey' "$power_broker"
grep -Fq 'SHORT_PRESS_SECONDS = 1.25' "$power_broker"
grep -Fq 'display_power_mode(connection)' "$power_broker"
grep -Fq 'set_display_power(connection, 0)' "$power_broker"
grep -Fq 'if handheld_sleeping(connection)' "$power_broker"
grep -Fq 'ExecStart=/usr/libexec/luma-power-key-broker' "$power_broker_service"
grep -Fq 'PartOf=luma-shell-session.target' "$power_broker_service"
grep -Fq 'WantedBy=luma-shell-session.target' "$power_broker_service"
! grep -Fq 'WantedBy=graphical-session.target' "$power_broker_service"
grep -Fq 'TAG+="uaccess"' "$power_rule"
grep -Fq 'LUMA_FP6_DISPLAY_POWER_ACCEPTANCE_VERSION=2' \
  "$display_power_acceptance"
grep -Fq 'short_press_once_to_blank_then_once_to_wake' \
  "$display_power_acceptance"
grep -Fq 'systemd-inhibit --list --no-legend' "$display_power_acceptance"
grep -Fq "renderer=phosh" "$display_power_acceptance"
grep -Fq 'Phosh handling power key' "$display_power_acceptance"
grep -Fq 'Luma raw power-key broker must be inactive while Phosh owns the key' \
  "$display_power_acceptance"
grep -Fq 'sudo -n journalctl -k' "$display_power_acceptance"
grep -Fq "[ -z \"\$gpu_faults\" ]" "$display_power_acceptance"
grep -Fq 'PERSISTENT_MUTATIONS=none' "$display_power_acceptance"
! grep -Eq '(^|[[:space:]])(reboot|poweroff|suspend|hibernate|systemctl restart|systemctl stop)([[:space:]]|$)' \
  "$display_power_acceptance"
PYTHONPYCACHEPREFIX=${TMPDIR:-/tmp}/luma-python-cache \
  python3 -m py_compile "$input_settings"
grep -Fq 'Screen turns off after' "$input_settings"
grep -Fq 'Stevia' "$input_settings"
grep -Fq 'Plasma Keyboard' "$input_settings"
grep -Fq 'Maliit Keyboard' "$input_settings"
grep -Fq 'Lomiri Keyboard' "$input_settings"
grep -Fq 'Sysboard' "$input_settings"
grep -Fq 'Wkeys' "$input_settings"
grep -Fq 'org.project_luma.MobileInputSettings.desktop' "$handheld_extension"
grep -Fq 'name="keyboard-engine"' "$handheld_schema"
grep -Fq "'gnome'" "$handheld_schema"
PYTHONPYCACHEPREFIX=${TMPDIR:-/tmp}/luma-python-cache \
  python3 -m py_compile "$latinime_engine"
grep -Fq 'APPROPRIATE_FOR_AUTOCORRECTION' "$latinime_engine"
grep -Fq 'PASSTHROUGH_PURPOSES' "$latinime_engine"
grep -Fq 'SENSITIVE_HINTS' "$latinime_engine"
grep -Fq 'org.project_luma.Keyboard1' "$latinime_engine"
grep -Fq '<name>luma-latin</name>' "$latinime_component"
grep -Fq "('ibus', 'luma-latin')" "$handheld_profile"
grep -Fq 'current=uint32 0' "$handheld_profile"
grep -Fq "completion-mode=['manual']" "$handheld_profile"
grep -Fq "default='luma'" "$handheld_profile"
grep -Fq "osk-features=['key-indicator']" "$handheld_profile"
sh -n "$keyboard_lab"
sh -n "$keyboard_lab_session"
PYTHONPYCACHEPREFIX=${TMPDIR:-/tmp}/luma-python-cache \
  python3 -m py_compile "$keyboard_lab_entry"
sh -n "$kwin_keyboard_engine"
sh -n "$wkeys_direct_session"
sh -n "$wkeys_direct_client"
sh -n "$lomiri_direct_session"
grep -Fq 'WLR_BACKENDS=drm,libinput' "$wkeys_direct_session"
grep -Fq 'exec /usr/local/bin/luma-shell-session' "$wkeys_direct_session"
grep -Fq -- '--what=handle-power-key' "$wkeys_direct_session"
grep -Fq -- '--layout "$root/layout.toml"' "$wkeys_direct_client"
grep -Fq 'top_legend = "Space"' "$wkeys_layout"
grep -Fq 'button:active' "$wkeys_style"
grep -Fq 'source_commit=a01d50b160fc8d5375fb208b20ae5781b5ce912e' \
  "$lomiri_keyboard_build"
grep -Fq 'liblomiri-keyboard-plugin.so' "$lomiri_keyboard_build"
grep -Fq 'lomiri-keyboard-emoji' "$lomiri_keyboard_build"
grep -Fq 'file "$plugin" | grep -q "ARM aarch64"' "$lomiri_keyboard_build"
grep -Fq 'a01d50b160fc8d5375fb208b20ae5781b5ce912e' \
  "$lomiri_runtime_packager"
grep -Fq 'luma-keyboard-lomiri-1.1.0-aarch64.tar.zst' \
  "$lomiri_runtime_packager"
grep -Fq -- '--drm --socket wayland-0' "$lomiri_direct_session"
grep -Fq -- '--what=handle-power-key' "$lomiri_direct_session"
grep -Fq 'exec /usr/local/bin/luma-shell-session' "$lomiri_direct_session"
grep -Fq 'WLR_BACKENDS=wayland' "$keyboard_lab"
grep -Fq '/usr/bin/phosh-osk-stevia --replace &' "$keyboard_lab_session"
grep -Fq 'candidate=/usr/libexec/luma-keyboard-labs/squeekboard' "$keyboard_lab"
grep -Fq 'SQUEEKBOARD_DEBUG=force-show' "$keyboard_lab_session"
grep -Fq 'GSETTINGS_SCHEMA_DIR=/usr/share/luma-keyboard-labs/squeekboard/schemas' "$keyboard_lab_session"
grep -Fq '/usr/libexec/luma-keyboard-labs/squeekboard &' "$keyboard_lab_session"
grep -Fq 'candidate=/usr/libexec/luma-keyboard-labs/wvkbd-mobintl' "$keyboard_lab"
grep -Fq '/usr/libexec/luma-keyboard-labs/wvkbd-mobintl' "$keyboard_lab_session"
grep -Fq 'candidate=/usr/libexec/luma-keyboard-labs/sysboard/sysboard' "$keyboard_lab"
grep -Fq 'layout=mobile' "$keyboard_lab_session"
grep -Fq 'LD_LIBRARY_PATH="$sysboard_root' "$keyboard_lab_session"
grep -Fq 'Lomiri Keyboard' "$input_settings"
grep -Fq '/var/lib/luma-keyboard-labs/kde-f44' "$keyboard_lab"
grep -Fq 'org.kde.kwin.VirtualKeyboard.forceActivate' "$keyboard_lab"
grep -Fq "org.kde.kwin.VirtualKeyboard mode '<int32 2>'" "$keyboard_lab"
grep -Fq 'LUMA_KWIN_KEYBOARD_ENGINE' "$kwin_keyboard_engine"
grep -Fq 'SetExternalKeyboardVisible' "$keyboard_lab_session"
grep -Fq 'sm.puri.OSK0.SetVisible true' "$keyboard_lab_session"
grep -Fq "grep -Fq '<true>'" "$keyboard_lab_session"
grep -Fq 'Nothing typed here is saved or logged' "$keyboard_lab_entry"
grep -Fq 'Test temporarily' "$input_settings"
grep -Fq "app.state === Shell.AppState.STARTING" "$handheld_extension"
grep -Fq "name: 'lumaHandheldLaunchSurface'" "$handheld_extension"
grep -Fq 'get_window_app(focused)' "$handheld_extension"
grep -Fq '.luma-handheld .luma-handheld-launch-surface' "$handheld_stylesheet"
grep -Fq 'idle-delay=uint32 60' "$handheld_profile"
grep -Fq "power-button-action='nothing'" "$handheld_profile"
grep -Fq '#panel.luma-handheld' "$handheld_stylesheet"
grep -Fq 'height: 42px' "$handheld_stylesheet"
grep -Fq 'background-color: #ffffff' "$handheld_stylesheet"
grep -Fq 'icon-size: 17px' "$handheld_stylesheet"
grep -Fq 'border-radius: 999px' "$handheld_stylesheet"
grep -Fq -- '-st-hfade-offset: 32px' "$handheld_stylesheet"
grep -Fq '.keyboard-key:active' "$handheld_stylesheet"
grep -Fq '#dashtodockContainer.bottom' "$handheld_stylesheet"

if grep -E 'console\.(log|warn|error).*(_startX|_startY|KEY_|keyval)' \
  "$handheld_extension"; then
  printf 'error: content-bearing input value is written to the Shell journal\n' >&2
  exit 1
fi

if grep -Eq '(^|[[:space:]])(ssh|scp|flash|erase|wipe|set[_-]active)([[:space:]]|$)' \
  "$build_script"; then
  printf 'error: live-device or mutation token found in offline shell builder\n' >&2
  exit 1
fi

printf 'Mobile Luma Shell AArch64 source contract: PASS\n'
