[terminal]
vt = 1
switch = true

[general]
source_profile = true

[initial_session]
command = "/usr/local/bin/luma-android-pixman-session"
user = "luma"

[default_session]
command = "agreety --cmd /usr/local/bin/luma-shell-session"
user = "greetd"
