layout = [
    [
        { top_legend = "Q", scan_code = 16 },
        { top_legend = "W", scan_code = 17 },
        { top_legend = "E", scan_code = 18 },
        { top_legend = "R", scan_code = 19 },
        { top_legend = "T", scan_code = 20 },
        { top_legend = "Y", scan_code = 21 },
        { top_legend = "U", scan_code = 22 },
        { top_legend = "I", scan_code = 23 },
        { top_legend = "O", scan_code = 24 },
        { top_legend = "P", scan_code = 25 },
    ],
    [
        { top_legend = "", scan_code = 0, width = 0.5 },
        { top_legend = "A", scan_code = 30 },
        { top_legend = "S", scan_code = 31 },
        { top_legend = "D", scan_code = 32 },
        { top_legend = "F", scan_code = 33 },
        { top_legend = "G", scan_code = 34 },
        { top_legend = "H", scan_code = 35 },
        { top_legend = "J", scan_code = 36 },
        { top_legend = "K", scan_code = 37 },
        { top_legend = "L", scan_code = 38 },
        { top_legend = "", scan_code = 0, width = 0.5 },
    ],
    [
        { top_legend = "Shift", scan_code = 42, width = 1.4 },
        { top_legend = "Z", scan_code = 44 },
        { top_legend = "X", scan_code = 45 },
        { top_legend = "C", scan_code = 46 },
        { top_legend = "V", scan_code = 47 },
        { top_legend = "B", scan_code = 48 },
        { top_legend = "N", scan_code = 49 },
        { top_legend = "M", scan_code = 50 },
        { top_legend = "⌫", scan_code = 14, width = 1.6 },
    ],
    [
        { top_legend = "?123", scan_code = 0, width = 1.2 },
        { top_legend = ",", scan_code = 51 },
        { top_legend = "Space", scan_code = 57, width = 4.6 },
        { top_legend = ".", scan_code = 52 },
        { top_legend = "Enter", scan_code = 28, width = 2.2 },
    ],
]
