#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the schema 4 Depot seed shipped in the package.

The seed is what Depot shows before it has ever verified a published catalogue,
and what the installer reads its suites from. It is built from two reviewed
inputs in this directory:

* ``depot-catalog.json`` -- the schema 3 listing (every entry becomes a Listed
  app: each installs from its publisher or Flathub);
* ``depot-first-party.json`` -- Project Luma's own apps and the launch
  collections;
* ``depot-verified.json`` -- verified developers' apps on the Luma remote;
* ``depot-channels.json`` -- the official channel each listing installs from
  when that is not its publisher's website (a verified snap, a signed package
  repository), the words written for Luma's own apps, and withdrawals;
* ``depot-listings.json`` -- generated by scripts/depot/enrich-listings.py from
  each publisher's own store metadata: icons, screenshots, descriptions,
  releases, sizes, sandbox permissions.

Entries whose visibility is ``private`` or ``withdrawn`` are never written:
a seed is public the moment the package is. Collections keep every member id,
so first-boot provisioning can install an app that becomes public later.

Output is deterministic; ``--check`` fails when the committed seed is stale.
"""

import argparse
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / 'data'
sys.path.insert(0, str(HERE.parent))

from luma_installer.depot_catalog import validate_catalog  # noqa: E402

LEGACY_CATEGORIES = {'gimp': 'create', 'audacity': 'create', 'obs': 'create', 'blender': 'create',
                     'inkscape': 'create', 'krita': 'create', 'kdenlive': 'create',
                     'spotify': 'media', 'vlc': 'media', 'steam': 'media',
                     'libreoffice': 'office', 'obsidian': 'work', 'thunderbird': 'communication',
                     'discord': 'communication', 'slack': 'communication', 'zoom': 'communication'}
PUBLIC = ('public', 'unlisted')
#: What an enriched listing may set on an entry. Everything else about an
#: entry -- its identity, tier, source and qualification -- is reviewed input.
LISTING_FIELDS = ('summary', 'description', 'license', 'homepage', 'support_url', 'source_url',
                  'privacy_url', 'categories', 'icon', 'screenshots', 'release', 'permissions',
                  'age_rating', 'architectures')
#: Channel fields that replace an entry's source. ``sources`` is merged.
CHANNEL_FIELDS = ('backend', 'repository', 'source_id', 'distribution', 'architectures', 'reference_url',
                  'qualification', 'qualification_reason', 'sign_in', 'visibility', 'homepage', 'publisher',
                  'summary', 'description', 'categories', 'channel', 'sandbox', 'system_tool', 'app_id',
                  'screenshots_pending')


def _slug(name):
    import re
    return (re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-') or 'publisher')[:48]


def _channel_label(entry, listing):
    """The ``channel`` object: where this listing installs from, for display."""
    if entry.get('channel'):
        return entry['channel']
    backend, repository = entry['backend'], entry['repository']
    verified = (listing or {}).get('publisher_verified', '')
    if backend == 'flatpak' and repository == 'luma':
        return {'kind': 'luma', 'title': 'Luma', 'publisher_verified': True}
    if backend == 'flatpak' and repository == 'flathub':
        return {'kind': 'flathub', 'title': 'Flathub', 'publisher_verified': verified == 'flathub',
                'community': entry.get('distribution') == 'community' and verified != 'flathub'}
    if backend == 'rpm' and repository == 'luma':
        return {'kind': 'luma', 'title': 'Luma', 'publisher_verified': True}
    if backend == 'rpm' and repository == 'fedora':
        return {'kind': 'fedora', 'title': 'Fedora', 'publisher_verified': False, 'community': True}
    return None


def _apply_listing(entry, listing):
    for field in LISTING_FIELDS:
        value = listing.get(field)
        if value in (None, '', [], {}):
            continue
        if field == 'permissions' and entry.get('backend') != 'flatpak':
            continue
        if field == 'permissions':
            # Depots before 1.luma.32 refuse a catalogue whose permission keys
            # carry a hyphen (system.ssh-agent); spell them with an underscore.
            value = [{**grant, 'key': grant['key'].replace('-', '_')} for grant in value]
        if field == 'architectures' and entry.get('backend') not in ('flatpak', 'snap'):
            continue
        if field == 'homepage' and entry.get('tier') == 'luma':
            continue
        if field in ('summary', 'description') and entry.get('tier') in ('luma', 'verified') and entry.get(field):
            continue
        entry[field] = value
    name = listing.get('developer_name')
    if name and not entry.get('developer'):
        entry['developer'] = {'id': 'pub_' + _slug(name).replace('-', '_'), 'name': name[:128]}
    if listing.get('sandbox') and not entry.get('sandbox'):
        entry['sandbox'] = listing['sandbox']


def generate(legacy_path=DATA / 'depot-catalog.json', first_party_path=DATA / 'depot-first-party.json',
             verified_path=DATA / 'depot-verified.json', generated_at=None,
             channels_path=DATA / 'depot-channels.json', listings_path=DATA / 'depot-listings.json'):
    legacy = json.loads(Path(legacy_path).read_text())
    first_party = json.loads(Path(first_party_path).read_text())
    verified = json.loads(Path(verified_path).read_text()) if Path(verified_path).is_file() else None
    channels = (json.loads(Path(channels_path).read_text()).get('applications', {})
                if channels_path and Path(channels_path).is_file() else {})
    listings = (json.loads(Path(listings_path).read_text()).get('listings', {})
                if listings_path and Path(listings_path).is_file() else {})
    applications = []
    for row in legacy['applications']:
        entry = dict(row)
        entry['tier'] = 'listed'
        entry['visibility'] = 'public'
        if entry['backend'] == 'flatpak':
            entry['app_id'] = entry['source_id']
        if entry['id'] in LEGACY_CATEGORIES:
            entry['categories'] = [LEGACY_CATEGORIES[entry['id']]]
        applications.append({key: entry[key] for key in sorted(entry)})
    for source in (first_party, verified):
        if source is None:
            continue
        defaults = source.get('defaults', {})
        for row in source['applications']:
            entry = {**defaults, **row}
            if entry.get('visibility') not in PUBLIC:
                continue
            entry.setdefault('reference_url', f"https://simplyluma.com/apps/{entry['id']}")
            entry.setdefault('homepage', entry['reference_url'])
            applications.append({key: entry[key] for key in sorted(entry)})
    enriched = []
    for entry in applications:
        channel = channels.get(entry['id'], {})
        for field in CHANNEL_FIELDS:
            if field in channel:
                entry[field] = channel[field]
        if channel.get('sources'):
            entry['sources'] = {**entry.get('sources', {}), **channel['sources']}
        if entry.get('visibility') not in PUBLIC:
            continue
        listing = listings.get(entry['id'])
        if listing:
            _apply_listing(entry, listing)
        label = _channel_label(entry, listing)
        if label:
            entry['channel'] = label
        enriched.append({key: entry[key] for key in sorted(entry)})
    applications = enriched
    applications.sort(key=lambda entry: entry['id'])
    seed = {
        'schema_version': 4,
        # The shipped seed is dated by its review so it stays deterministic; a
        # published catalogue carries the moment it was made, because devices
        # refuse one older than the copy they already verified.
        'generated_at': generated_at or legacy['reviewed_on'] + 'T00:00:00Z',
        'collections': first_party.get('collections', []),
        'applications': applications,
    }
    validate_catalog(seed)
    return json.dumps(seed, indent=2, ensure_ascii=False) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('output', nargs='?', default=str(DATA / 'depot-catalog-4.json'))
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--generated-at', help='ISO 8601 UTC time for a published catalogue')
    options = parser.parse_args(argv)
    text = generate(generated_at=options.generated_at)
    output = Path(options.output)
    if options.check:
        if not output.is_file() or output.read_text() != text:
            print(f'{output} is stale; run {Path(__file__).name}', file=sys.stderr)
            return 1
        return 0
    output.write_text(text)
    print(f'wrote {output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
