[storage]
driver = "overlay"
runroot = "/srv/luma-build/containers/runroot"
graphroot = "/srv/luma-build/containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,metacopy=on"
