/* SPDX-License-Identifier: ISC AND MIT
 * ISC License
 *
 * Copyright (c) 2026 Lucide Icons and Contributors
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * ---
 *
 * The following Lucide icons are derived from the Feather project:
 *
 * airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out
 *
 * The MIT License (MIT) (for the icons listed above)
 *
 * Copyright (c) 2013-present Cole Bemis
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/* Generated by scripts/developer/generate-luma-frame-glyphs.py.
 * Lucide symbolic geometry, ISC; see assets/icon-theme/Prairie/upstream/lucide/lumaui/LICENSE.txt.
 * Exact native LumaUI control SVGs, rasterized at the shared control_icon size. */
#pragma once
#include <stdint.h>
#define LUMA_FRAME_GLYPH_SIZE 14
/* assets/icon-theme/Prairie/symbolic/actions/lumaui-minus-symbolic.svg SHA256 161b43c73129331e7aed6bc43a3bac4df3eefc529365e248ae7ab890303481b5 */
static const uint8_t luma_frame_minimize_glyph[196] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,51,119,119,119,119,119,119,119,119,51,0,0,
    0,0,51,119,119,119,119,119,119,119,119,51,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
/* assets/icon-theme/Prairie/symbolic/actions/lumaui-maximize-2-symbolic.svg SHA256 64d61565acb4bfa678f6931d594227682a6989025e74585c0065427ebdc656b2 */
static const uint8_t luma_frame_maximize_glyph[196] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,116,187,187,201,177,0,
    0,0,0,0,0,0,0,0,27,51,95,236,198,0,
    0,0,0,0,0,0,0,0,0,51,223,98,182,0,
    0,0,0,0,0,0,0,0,51,223,55,55,182,0,
    0,0,0,0,0,0,0,35,225,55,0,27,112,0,
    0,0,0,0,0,0,0,10,34,0,0,0,0,0,
    0,0,0,0,0,34,10,0,0,0,0,0,0,0,
    0,112,27,0,55,225,35,0,0,0,0,0,0,0,
    0,182,55,51,223,55,0,0,0,0,0,0,0,0,
    0,182,95,223,55,0,0,0,0,0,0,0,0,0,
    0,198,236,95,51,27,0,0,0,0,0,0,0,0,
    0,177,201,187,187,112,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
/* assets/icon-theme/Prairie/symbolic/actions/lumaui-minimize-2-symbolic.svg SHA256 c7326118a6d3a45cb46cdcebd98cc65fb48b90193be55a851d7b7e476d2beb67 */
static const uint8_t luma_frame_restore_glyph[196] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,1,13,0,0,54,109,0,
    0,0,0,0,0,0,0,71,156,0,55,225,55,0,
    0,0,0,0,0,0,0,76,161,51,223,55,0,0,
    0,0,0,0,0,0,0,76,180,223,55,0,0,0,
    0,0,0,0,0,0,0,100,251,175,153,150,11,0,
    0,0,0,0,0,0,0,20,93,68,68,65,2,0,
    0,2,65,68,68,93,20,0,0,0,0,0,0,0,
    0,11,150,153,175,251,100,0,0,0,0,0,0,0,
    0,0,0,51,223,181,76,0,0,0,0,0,0,0,
    0,0,51,223,55,161,76,0,0,0,0,0,0,0,
    0,55,225,55,0,156,71,0,0,0,0,0,0,0,
    0,109,54,0,0,13,1,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
/* assets/icon-theme/Prairie/symbolic/actions/lumaui-x-symbolic.svg SHA256 06d00634a42e66168fa2655935ad1dbd8e40fbb00457324ec5c2d8aaf1d96776 */
static const uint8_t luma_frame_close_glyph[196] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,194,55,0,0,0,0,55,194,0,0,0,
    0,0,0,50,223,56,0,0,51,223,55,0,0,0,
    0,0,0,0,50,223,56,51,223,55,0,0,0,0,
    0,0,0,0,0,50,229,230,55,0,0,0,0,0,
    0,0,0,0,0,51,229,230,56,0,0,0,0,0,
    0,0,0,0,51,223,55,50,223,56,0,0,0,0,
    0,0,0,51,223,55,0,0,50,223,56,0,0,0,
    0,0,0,194,55,0,0,0,0,55,194,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
/* assets/icon-theme/Prairie/symbolic/actions/lumaui-chevron-left-symbolic.svg SHA256 f0503285c5356f81bccc1bd5af9c5b1b2a0dcb85230f827ec3d21042cbf39964 */
static const uint8_t luma_frame_back_glyph[196] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,21,200,28,0,0,0,0,
    0,0,0,0,0,0,21,209,107,0,0,0,0,0,
    0,0,0,0,0,21,209,107,0,0,0,0,0,0,
    0,0,0,0,13,209,105,0,0,0,0,0,0,0,
    0,0,0,0,13,209,105,0,0,0,0,0,0,0,
    0,0,0,0,0,21,209,108,0,0,0,0,0,0,
    0,0,0,0,0,0,21,209,108,0,0,0,0,0,
    0,0,0,0,0,0,0,21,200,28,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};
