#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0
"""Declare the image's /var content as systemd-tmpfiles entries.

A deployed OSTree system never receives /var from its commit; /var belongs to
the machine. rpm-ostree therefore turns package-owned /var directories and
links into tmpfiles.d lines (rpm-ostree-autovar.conf) when it composes. A
container-built image needs the same translation, or those directories are
simply missing after install. This writes /usr/lib/tmpfiles.d/luma-autovar.conf
for every directory and symlink below /var that no tmpfiles.d line declares
yet. Regular files are declared too: an empty one becomes an `f` line, a
non-empty one is kept in /usr/share/factory/var and copied with a `C` line.
"""

import grp
import os
import pwd
import shutil
import stat
import subprocess
import sys

SKIP = ("/var/tmp", "/var/cache/libdnf5", "/var/log/dnf5.log", "/var/roothome", "/var/home")
OUTPUT = "/usr/lib/tmpfiles.d/luma-autovar.conf"
FACTORY = "/usr/share/factory"


def declared_paths():
    text = subprocess.run(["systemd-tmpfiles", "--cat-config"], capture_output=True, text=True, check=True).stdout
    paths = set()
    for line in text.splitlines():
        fields = line.split()
        if len(fields) >= 2 and not fields[0].startswith("#"):
            paths.add(fields[1].rstrip("/"))
    return paths


def owner(st):
    try:
        user = pwd.getpwuid(st.st_uid).pw_name
    except KeyError:
        user = str(st.st_uid)
    try:
        group = grp.getgrgid(st.st_gid).gr_name
    except KeyError:
        group = str(st.st_gid)
    return user, group


def main():
    declared = declared_paths()
    lines = []
    for root, dirs, files in os.walk("/var", topdown=True):
        dirs[:] = sorted(d for d in dirs if not os.path.join(root, d).startswith(SKIP))
        for name in sorted(dirs) + sorted(files):
            path = os.path.join(root, name)
            if path.startswith(SKIP) or path in declared:
                continue
            st = os.lstat(path)
            user, group = owner(st)
            mode = f"{stat.S_IMODE(st.st_mode):04o}"
            if stat.S_ISLNK(st.st_mode):
                lines.append(f"L {path} - - - - {os.readlink(path)}")
            elif stat.S_ISDIR(st.st_mode):
                lines.append(f"d {path} {mode} {user} {group} - -")
            elif stat.S_ISREG(st.st_mode):
                if path.startswith(("/var/cache/", "/var/log/")):
                    continue  # caches and logs are never factory content
                if st.st_size == 0:
                    lines.append(f"f {path} {mode} {user} {group} -")
                else:
                    factory = FACTORY + path
                    os.makedirs(os.path.dirname(factory), exist_ok=True)
                    shutil.copy2(path, factory)
                    lines.append(f"C {path} - - - - {factory}")
                    lines.append(f"z {path} {mode} {user} {group} -")
    if lines:
        with open(OUTPUT, "w", encoding="utf-8") as stream:
            stream.write("# Generated by the Luma image build (image/luma-desktop/scripts/var-to-tmpfiles.py).\n")
            stream.write("\n".join(lines) + "\n")
    print(f"declared {len(lines)} /var entries in {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
