#!/bin/sh
# SPDX-License-Identifier: Apache-2.0

# Build only the bounded QCOMTEE kernel-privilege control module against the
# exact accepted FP6 kernel symbol table. This avoids rebuilding or replacing
# the running kernel and produces a temporary signed module for one control TA.

set -eu
umask 022

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
build_root=${1:?usage: build-fp6-qcomtee-control-module.sh BASE_BUILD_ROOT OUTPUT_DIR}
output_dir=${2:?missing output directory}
source_tree=$build_root/lab/root/work/linux
work_tree=$build_root/lab/root/work/linux-qcomtee-control-v18
overlay=$repo_root/src/fp6-fingerprint-qcomtee/qcomtee-control.c
patch_file=$repo_root/patches/linux-qcomtee-control-v18/0001-qcomtee-add-bounded-luma-control-identity-hook.patch
kernel_release=7.1.2-luma-fp-cma1
localversion=-luma-fp-cma1
jobs=${LUMA_KERNEL_BUILD_JOBS:-8}
expected_config_sha=a403b3cb247d3f2ce358f8debcc3b93d3c1949813488da8e12ac81540cee519c
expected_kernel_sha=101fafec6d1d661b1b159d69e43c14d1289ca03f0944af4d5593b10662524572
expected_symvers_sha=95305a0ce0ee9993a71ccd5075e38ae7b6de942a9adbf90c8d9a81f3d606aeea
expected_key_sha=94f151fcd2cec29112beb22cf226ea9cc2acb5f000de05b518ffab7657e14220
expected_cert_sha=f189a9fb1adcb102271a3ce6904bc998e05aaf14e5ccd5b9147c67301fa28749
expected_overlay_sha=1c440ce62eb646c0ffdef2ab9549dd46aced268a3b0a6e262002bab4688a53b1
expected_patch_sha=24d490ef7ac4bf53fd660efa7bc89d50c42993e47b2a082788e3bd55f7206a89

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
hash() { sha256sum "$1" | awk '{print $1}'; }

case "$jobs" in ''|*[!0-9]*) die 'LUMA_KERNEL_BUILD_JOBS must be numeric' ;; esac
[ "$jobs" -ge 1 ] || die 'LUMA_KERNEL_BUILD_JOBS must be positive'
[ "$(id -u)" -eq 0 ] || die 'run as root in the isolated builder'
[ "$(uname -s)" = Linux ] && [ "$(uname -m)" = aarch64 ] ||
  die 'builder must be Linux/aarch64'
clang --version | head -n 1 | grep -Fx 'Ubuntu clang version 21.1.8 (6ubuntu1)' >/dev/null ||
  die 'native AArch64 Clang 21.1.8 differs'
[ ! -e "$work_tree" ] || die 'work tree already exists'
[ ! -e "$output_dir" ] || die 'output directory already exists'
[ "$(hash "$source_tree/.config")" = "$expected_config_sha" ] || die 'base config differs'
[ "$(hash "$source_tree/arch/arm64/boot/vmlinuz")" = "$expected_kernel_sha" ] || die 'base kernel differs'
[ "$(hash "$source_tree/Module.symvers")" = "$expected_symvers_sha" ] || die 'base symbol table differs'
[ "$(hash "$source_tree/certs/signing_key.pem")" = "$expected_key_sha" ] || die 'signing key differs'
[ "$(hash "$overlay")" = "$expected_overlay_sha" ] || die 'control source differs'
[ "$(hash "$patch_file")" = "$expected_patch_sha" ] || die 'integration patch differs'

cp -al "$source_tree" "$work_tree"
(
  cd "$work_tree"
  make ARCH=arm64 LLVM=1 LOCALVERSION="$localversion" clean
  scripts/config --module QCOMTEE
  make ARCH=arm64 LLVM=1 LOCALVERSION="$localversion" olddefconfig
  grep -qx 'CONFIG_QCOMTEE=m' .config || die 'QCOMTEE config differs'
  make -j"$jobs" ARCH=arm64 LLVM=1 LOCALVERSION="$localversion" modules_prepare
  [ "$(hash Module.symvers)" = "$expected_symvers_sha" ] ||
    die 'prepared symbol table differs'
  patch -p1 --fuzz=0 --no-backup-if-mismatch <"$patch_file"
  install -m 0644 "$overlay" drivers/tee/qcomtee/qcomtee-control.c
  make -j"$jobs" ARCH=arm64 LLVM=1 LOCALVERSION="$localversion" \
    KBUILD_BUILD_USER=pmos KBUILD_BUILD_HOST=build \
    KBUILD_BUILD_TIMESTAMP='2026-08-23 00:00:00 UTC' \
    KBUILD_BUILD_VERSION=1-postmarketos \
    M=drivers/tee/qcomtee modules
  [ "$(make ARCH=arm64 LLVM=1 LOCALVERSION="$localversion" -s kernelrelease)" = "$kernel_release" ] ||
    die 'kernel release differs'
  file scripts/sign-file | grep -Fq 'ARM aarch64' || die 'sign-file is not native AArch64'
  openssl x509 -in "$source_tree/certs/signing_key.pem" -out control-signing.x509.pem
  [ "$(hash control-signing.x509.pem)" = "$expected_cert_sha" ] ||
    die 'derived signing certificate differs'
  scripts/sign-file sha512 "$source_tree/certs/signing_key.pem" \
    control-signing.x509.pem drivers/tee/qcomtee/qcomtee.ko
)

mkdir -p "$output_dir"
install -m 0644 "$work_tree/drivers/tee/qcomtee/qcomtee.ko" "$output_dir/qcomtee-control.ko"
vermagic=$(modinfo -F vermagic "$output_dir/qcomtee-control.ko")
[ "${vermagic%% *}" = "$kernel_release" ] || die 'module vermagic differs'
[ "$(modinfo -F name "$output_dir/qcomtee-control.ko")" = qcomtee ] || die 'module name differs'
[ -z "$(modinfo -F depends "$output_dir/qcomtee-control.ko")" ] || die 'module dependencies differ'
[ "$(modinfo -F signer "$output_dir/qcomtee-control.ko")" = 'Build time autogenerated kernel key' ] ||
  die 'module signer differs'
[ "$(modinfo -F sig_hashalgo "$output_dir/qcomtee-control.ko")" = sha512 ] ||
  die 'module signature algorithm differs'

{
  printf 'LUMA_FP6_QCOMTEE_CONTROL_BUILD_VERSION=18\n'
  printf 'KERNEL_RELEASE=%s\n' "$kernel_release"
  printf 'BASE_CONFIG_SHA256=%s\n' "$expected_config_sha"
  printf 'BASE_KERNEL_SHA256=%s\n' "$expected_kernel_sha"
  printf 'BASE_MODULE_SYMVERS_SHA256=%s\n' "$expected_symvers_sha"
  printf 'CONTROL_SOURCE_SHA256=%s\n' "$expected_overlay_sha"
  printf 'INTEGRATION_PATCH_SHA256=%s\n' "$expected_patch_sha"
  printf 'MODULE_SHA256=%s\n' "$(hash "$output_dir/qcomtee-control.ko")"
  printf 'MODULE_SIGNED=true\n'
  printf 'CONTROL_APP=smplap64\n'
  printf 'TA_COMMANDS_ALLOWED=false\n'
  printf 'BIOMETRIC_COMMANDS_ALLOWED=false\n'
  printf 'PHONE_ACCESSED=false\n'
  printf 'PARTITION_WRITTEN=false\n'
} >"$output_dir/manifest.env"
chmod 0644 "$output_dir/manifest.env"

find "$work_tree" -depth -delete
printf 'FP6 QCOMTEE control module: %s\n' "$output_dir/qcomtee-control.ko"
