#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# Compile the exact unmodified Tokay secondary U-Boot tree as an off-device
# source/toolchain proof. The resulting binary is not an authorized payload:
# its shell and write-capable USB update interface must not be exposed to the
# phone during initial validation.

set -euo pipefail
umask 022

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
# shellcheck disable=SC1091
. "$repo_root/config/mobile/pixel9-physical/inputs.env"

source_root=${1:?usage: build-pixel9-uboot-proof.sh SOURCE_ROOT OUTPUT_DIR}
output_dir=${2:?usage: build-pixel9-uboot-proof.sh SOURCE_ROOT OUTPUT_DIR}
build_dir=$output_dir/build
artifact_dir=$output_dir/artifacts
jobs=${LUMA_PIXEL9_UBOOT_BUILD_JOBS:-4}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

case "$jobs" in
  ''|*[!0-9]*) die 'LUMA_PIXEL9_UBOOT_BUILD_JOBS must be a positive integer' ;;
esac
[ "$jobs" -ge 1 ] || die 'LUMA_PIXEL9_UBOOT_BUILD_JOBS must be at least 1'
[ "$(uname -s)" = Linux ] && [ "$(uname -m)" = aarch64 ] ||
  die 'the Pixel 9 U-Boot proof must run off-device on Linux/aarch64'

if [ -r /sys/firmware/devicetree/base/model ]; then
  build_device=$(tr -d '\000' </sys/firmware/devicetree/base/model)
  case "$build_device" in
    *Pixel*|*tokay*|*Tokay*) die 'refusing to compile on a Pixel target' ;;
  esac
fi

for tool in awk gcc git install make sha256sum; do
  command -v "$tool" >/dev/null 2>&1 || die "missing U-Boot build tool: $tool"
done
case "$(gcc -dumpmachine)" in
  aarch64*) ;;
  *) die 'native GCC target is not AArch64' ;;
esac

uboot=$source_root/u-boot-zumapro
source_manifest=$source_root/luma-source-manifest.env
[ -d "$uboot/.git" ] || die "missing full U-Boot checkout: $uboot"
[ -f "$source_manifest" ] || die "missing full-source manifest: $source_manifest"
[ ! -e "$output_dir" ] || die "refusing to replace existing output: $output_dir"

[ "$(git -C "$uboot" rev-parse HEAD)" = "$PIXEL9_UBOOT_COMMIT" ] ||
  die 'U-Boot checkout differs from the pinned commit'
[ -z "$(git -C "$uboot" status --porcelain --untracked-files=no)" ] ||
  die 'U-Boot checkout contains tracked modifications'
defconfig_sha=$(sha256sum "$uboot/configs/$PIXEL9_UBOOT_DEFCONFIG" | awk '{print $1}')
[ "$defconfig_sha" = "$PIXEL9_UBOOT_DEFCONFIG_SHA256" ] ||
  die 'Tokay U-Boot defconfig checksum differs'
grep -Fqx "UBOOT_COMMIT=$PIXEL9_UBOOT_COMMIT" "$source_manifest" ||
  die 'full-source manifest does not match the U-Boot pin'
grep -Fqx 'PHONE_ACCESSED=false' "$source_manifest" ||
  die 'full-source manifest lacks the no-phone boundary'

mkdir -p "$build_dir" "$artifact_dir"
source_date_epoch=$(git -C "$uboot" show -s --format=%ct "$PIXEL9_UBOOT_COMMIT")
export SOURCE_DATE_EPOCH="$source_date_epoch"
export KBUILD_BUILD_TIMESTAMP="@$source_date_epoch"
export KBUILD_BUILD_USER=luma
export KBUILD_BUILD_HOST=pixel9-builder
export KBUILD_BUILD_VERSION=1

make -C "$uboot" O="$build_dir" ARCH=arm CROSS_COMPILE= \
  "$PIXEL9_UBOOT_DEFCONFIG"
make -C "$uboot" O="$build_dir" ARCH=arm CROSS_COMPILE= -j"$jobs"

for artifact in u-boot.bin u-boot.dtb .config include/generated/env.txt; do
  [ -s "$build_dir/$artifact" ] || die "U-Boot proof artifact is missing: $artifact"
done
install -m 0644 "$build_dir/u-boot.bin" "$artifact_dir/u-boot.bin"
install -m 0644 "$build_dir/u-boot.dtb" "$artifact_dir/u-boot.dtb"
install -m 0644 "$build_dir/.config" "$artifact_dir/config"
install -m 0644 "$build_dir/include/generated/env.txt" "$artifact_dir/default-env.txt"

uboot_version=$(sed -n 's/^#define PLAIN_VERSION "\(.*\)"/\1/p' \
  "$build_dir/include/generated/version_autogenerated.h")
compiler_line=$(gcc --version | sed -n '1p' | tr '\n' ' ')
{
  printf 'LUMA_PIXEL9_UBOOT_PROOF_VERSION=1\n'
  printf 'SCOPE=compile-only-unmodified-upstream\n'
  printf 'UBOOT_COMMIT=%s\n' "$PIXEL9_UBOOT_COMMIT"
  printf 'DEFCONFIG=%s\n' "$PIXEL9_UBOOT_DEFCONFIG"
  printf 'DEFCONFIG_SHA256=%s\n' "$PIXEL9_UBOOT_DEFCONFIG_SHA256"
  printf 'SOURCE_DATE_EPOCH=%s\n' "$source_date_epoch"
  printf 'UBOOT_VERSION=%s\n' "$uboot_version"
  printf 'COMPILER=%s\n' "$compiler_line"
  printf 'UBOOT_BIN_SHA256=%s\n' "$(sha256sum "$artifact_dir/u-boot.bin" | awk '{print $1}')"
  printf 'UBOOT_DTB_SHA256=%s\n' "$(sha256sum "$artifact_dir/u-boot.dtb" | awk '{print $1}')"
  printf 'CONFIG_SHA256=%s\n' "$(sha256sum "$artifact_dir/config" | awk '{print $1}')"
  printf 'DEFAULT_ENV_SHA256=%s\n' "$(sha256sum "$artifact_dir/default-env.txt" | awk '{print $1}')"
  printf 'BUILD_HOST=Linux/aarch64\n'
  printf 'PHONE_ACCESSED=false\n'
  printf 'ANDROID_BOOT_IMAGE_ASSEMBLED=false\n'
  printf 'U_BOOT_FASTBOOT_EXPOSED=false\n'
  printf 'U_BOOT_SHELL_EXPOSED=false\n'
  printf 'BOOT_AUTHORIZED=false\n'
  printf 'FLASH_AUTHORIZED=false\n'
} >"$output_dir/manifest.env"
chmod 0644 "$output_dir/manifest.env"

printf 'Pixel 9 compile-only U-Boot proof: %s\n' "$output_dir"
