#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# Install a hash-pinned FP6 camera module bundle alongside the stock modules.
# Installation never loads or unloads a module. An existing Luma overlay is
# moved to a recoverable backup outside the depmod search tree before the new
# overlay is made visible.

set -euo pipefail
umask 022

expected_kernel=7.1.2
install_root=/usr/lib/modules/$expected_kernel/updates/luma-fp6-camera
state_root=/var/lib/luma-fp6-camera

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

[ "$(id -u)" -eq 0 ] || die 'run as root'
[ "$(uname -r)" = "$expected_kernel" ] || die 'unexpected running kernel'
tr '\0' '\n' </proc/device-tree/compatible | grep -Fxq fairphone,fp6 ||
  die 'device is not a Fairphone 6'

if [ "${1:-}" = --remove ]; then
  [ "$#" -eq 1 ] || die 'usage: install-fp6-camera-modules.sh --remove'
  [ ! -e "$install_root" ] || die 'refusing destructive removal; restore a pinned bundle instead'
  printf 'No Luma FP6 camera module overlay is installed.\n'
  exit 0
fi

bundle=${1:?usage: install-fp6-camera-modules.sh BUNDLE_DIR}
manifest=$bundle/manifest.env
[ -f "$manifest" ] || die 'bundle manifest is missing'

# The manifest is generated by our build script and must contain only simple
# KEY=VALUE records before it is sourced as data.
if grep -Evq '^[A-Z0-9_]+=[A-Za-z0-9._-]+$' "$manifest"; then
  die 'bundle manifest contains unexpected syntax'
fi
# shellcheck disable=SC1090
. "$manifest"

case "${LUMA_FP6_CAMERA_ALL_SENSOR_BUILD_VERSION:-}" in
  2|3|4|5)
    [ "${KERNEL_RELEASE:-}" = "$expected_kernel" ] || die 'bundle kernel differs'
    [ "${RAM_LOAD_ONLY:-}" = true ] || die 'bundle provenance flag differs'
    [ "${PARTITION_WRITTEN:-}" = false ] || die 'bundle provenance flag differs'
    modules=(v4l2-cci qcom-camss ov13b10 dw9714 dw9784 s5kkd1sp imx896)
    hashes=(
      "$V4L2_CCI_KO_SHA256"
      "$QCOM_CAMSS_KO_SHA256"
      "$OV13B10_KO_SHA256"
      "$DW9714_KO_SHA256"
      "$DW9784_KO_SHA256"
      "$S5KKD1SP_KO_SHA256"
      "$IMX896_KO_SHA256"
    )
    # Include a module hash so a rebuilt bundle using the same DTB receives a
    # distinct, recoverable backup directory instead of colliding with an
    # earlier installation of that device tree.
    bundle_id=${QCOM_CAMSS_KO_SHA256:0:16}
    ;;
  *)
    die 'unsupported camera bundle version'
    ;;
esac

for index in "${!modules[@]}"; do
  module=$bundle/${modules[$index]}.ko
  [ -f "$module" ] || die "missing module: ${modules[$index]}"
  [ "$(sha256sum "$module" | awk '{print $1}')" = "${hashes[$index]}" ] ||
    die "module checksum differs: ${modules[$index]}"
  [ "$(modinfo -F vermagic "$module" | awk '{print $1}')" = "$expected_kernel" ] ||
    die "module vermagic differs: ${modules[$index]}"
  ! readelf -SW "$module" | grep -q '[.]BTF' ||
    die "module retains incompatible split BTF: ${modules[$index]}"
done

if [ -f "$install_root/manifest.env" ] && cmp -s "$manifest" "$install_root/manifest.env"; then
  printf 'The verified FP6 camera module bundle is already installed.\n'
  exit 0
fi

mkdir -p "$state_root/backups" "$state_root/failed"
backup_root=$state_root/backups/module-overlay-before-$bundle_id
failed_root=$state_root/failed/module-overlay-$bundle_id
[ ! -e "$backup_root" ] || die "backup already exists: $backup_root"
[ ! -e "$failed_root" ] || die "failed-install record already exists: $failed_root"

had_previous=false
if [ -e "$install_root" ]; then
  mv "$install_root" "$backup_root"
  had_previous=true
fi

rollback_install=true
cleanup_install() {
  if [ "$rollback_install" = true ]; then
    if [ -e "$install_root" ]; then
      mv "$install_root" "$failed_root" 2>/dev/null || true
    fi
    if [ "$had_previous" = true ] && [ -e "$backup_root" ]; then
      mv "$backup_root" "$install_root" 2>/dev/null || true
    fi
    depmod "$expected_kernel" 2>/dev/null || true
  fi
}
trap cleanup_install EXIT

mkdir -p "$install_root"
for module in "${modules[@]}"; do
  install -m 0644 "$bundle/$module.ko" "$install_root/$module.ko"
done
install -m 0644 "$manifest" "$install_root/manifest.env"
depmod "$expected_kernel"

for module in "${modules[@]}"; do
  selected=$(modinfo -n "$module")
  [ "$(readlink -f "$selected")" = "$(readlink -f "$install_root/$module.ko")" ] ||
    die "modprobe did not select the Luma overlay for $module: $selected"
done

rollback_install=false
trap - EXIT
printf 'Installed the verified FP6 camera modules without loading them.\n'
if [ "$had_previous" = true ]; then
  printf 'Previous overlay backup: %s\n' "$backup_root"
fi
