#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# Bounded FP6 physical gate for Fairphone's real kernel-privileged
# QSEEComCompat acquisition path. The signed temporary QCOMTEE module can load
# only Qualcomm's non-biometric smplap64 control, never obtains or invokes the
# TA application object, unloads the compatibility controller immediately, and
# restores every ephemeral resource on exit.

set -Eeuo pipefail
umask 077

stage=/tmp/luma-fingerprint-qcomtee-control-v18
firmware_path=/sys/module/firmware_class/parameters/path
expected_old_firmware_path=/lib/firmware/postmarketos
expected_model='The Fairphone (Gen. 6)'
expected_kernel=7.1.2-luma-fp-cma1
expected_boot_size=100663296
expected_boot_sha=c6acad3a30d944d59648258eef383c33a3b51ac1148a98ef24256ee4dee61dd8
expected_config_sha=5bddfee4390b0f66de5709b99282e79ee3787a01749d5cc8d28ea82d6bbed7fe
expected_installed_qsee_sha=047100c255b64b14ec1565cfc089f9bd0c5eb3a28e67b259f206bc930af39f5b
expected_installed_focal_sha=be860585db2c68ca80b3ee9e5e4929413c0d7207f9524ba489f974c46e26d051
expected_module_sha=f4e7699f6a4cfe9aa075600c2c61e43cac3ba7a8f3c28629d82ec2ead37dc675
expected_bundle_sha=cf447217e7251b74db542cfaecaa001d0a36603dd1053c38d7298efce73a7f74

module_loaded=false
old_firmware_path=
cleaned=false
baseline_dmesg_lines=0

fail() {
  printf 'event=qcomtee_privileged_control_v18_failed reason=%s\n' "$1" >&2
  exit 1
}

critical_faults() {
  grep -Ei \
    'page allocation failure|allocation failed|WARNING: CPU|hangcheck|GMU.*(timeout|fault)|GPU.*(timeout|fault|hang)|qsee.*(fault|timeout)|qcomtee.*(fault|timeout)|TEE.*(fault|timeout)|SCM.*(fault|timeout)|BUG:|kernel panic|Oops:|Call trace:' \
    || true
}

cleanup() {
  local status=$?
  local cleanup_status=0
  set +e
  if [[ $cleaned != true ]]; then
    if [[ -n $old_firmware_path && -w $firmware_path ]]; then
      printf '%s' "$old_firmware_path" >"$firmware_path" || cleanup_status=1
    fi
    if [[ $module_loaded == true ]] && grep -qw qcomtee /proc/modules; then
      rmmod qcomtee || cleanup_status=1
    fi
    if grep -qw qcomtee /proc/modules; then
      printf 'event=qcomtee_privileged_control_v18_cleanup_error reason=module_still_loaded\n' >&2
      cleanup_status=1
    fi
    if [[ -d $stage && ! -L $stage && $stage == /tmp/luma-fingerprint-qcomtee-control-v18 ]]; then
      find "$stage" -depth -delete || cleanup_status=1
    else
      printf 'event=qcomtee_privileged_control_v18_cleanup_error reason=stage_identity\n' >&2
      cleanup_status=1
    fi
    cleaned=true
  fi
  printf 'event=qcomtee_privileged_control_v18_cleanup firmware_path=%s module_loaded=%s stage_present=%s\n' \
    "$(cat "$firmware_path" 2>/dev/null || printf unavailable)" \
    "$(grep -qw qcomtee /proc/modules && printf true || printf false)" \
    "$([[ -e $stage ]] && printf true || printf false)"
  if (( cleanup_status != 0 && status == 0 )); then
    return "$cleanup_status"
  fi
  return "$status"
}
trap cleanup EXIT INT TERM HUP

[[ $(id -u) -eq 0 ]] || fail not_root
[[ -d $stage && ! -L $stage ]] || fail stage_identity
[[ $(find "$stage" -type f | wc -l) -eq 10 ]] || fail staged_file_count
[[ $(find "$stage" -type l | wc -l) -eq 0 ]] || fail staged_symlink
[[ $(tr -d '\0' </sys/firmware/devicetree/base/model) == "$expected_model" ]] || fail model
grep -qw 'androidboot.slot_suffix=_b' /proc/cmdline || fail slot
[[ $(uname -r) == "$expected_kernel" ]] || fail kernel
[[ $(head -c "$expected_boot_size" /dev/disk/by-partlabel/boot_b | sha256sum | cut -d' ' -f1) == "$expected_boot_sha" ]] || fail boot_hash
runtime_config=$(gzip -dc /proc/config.gz)
[[ $(sha256sum <<<"$runtime_config" | cut -d' ' -f1) == "$expected_config_sha" ]] || fail runtime_config_hash
grep -qx 'CONFIG_QCOM_TZMEM=y' <<<"$runtime_config" || fail tzmem_config
grep -qx 'CONFIG_QCOM_TZMEM_MODE_SHMBRIDGE=y' <<<"$runtime_config" || fail shmbridge_config
grep -qx '# CONFIG_QCOMTEE is not set' <<<"$runtime_config" || fail qcomtee_already_in_kernel
[[ $(sha256sum /usr/lib/modules/7.1.2-luma-fp-cma1/kernel/drivers/tee/qseecom/qseecomtee.ko.zst | cut -d' ' -f1) == "$expected_installed_qsee_sha" ]] || fail installed_qsee_hash
[[ $(sha256sum /usr/lib/modules/7.1.2-luma-fp-cma1/kernel/drivers/input/finger/focal_finger/focaltech_fp.ko.zst | cut -d' ' -f1) == "$expected_installed_focal_sha" ]] || fail installed_focal_hash
[[ $(sha256sum "$stage/qcomtee-control.ko" | cut -d' ' -f1) == "$expected_module_sha" ]] || fail staged_module_hash
[[ $(modinfo -F vermagic "$stage/qcomtee-control.ko" | awk '{print $1}') == "$expected_kernel" ]] || fail module_vermagic
[[ $(modinfo -F name "$stage/qcomtee-control.ko") == qcomtee ]] || fail module_name
[[ -z $(modinfo -F depends "$stage/qcomtee-control.ko") ]] || fail module_dependencies
[[ $(modinfo -F signer "$stage/qcomtee-control.ko") == 'Build time autogenerated kernel key' ]] || fail module_signer
[[ $(modinfo -F sig_hashalgo "$stage/qcomtee-control.ko") == sha512 ]] || fail module_signature_algorithm

[[ $(find "$stage/firmware" -maxdepth 1 -type f -name 'smplap64.b??' | wc -l) -eq 9 ]] || fail trustlet_file_count
bundle_sha=$(
  cd "$stage/firmware"
  sha256sum \
    smplap64.b00 smplap64.b01 smplap64.b02 smplap64.b03 smplap64.b04 \
    smplap64.b05 smplap64.b06 smplap64.b07 smplap64.b08 |
    sha256sum | cut -d' ' -f1
)
[[ $bundle_sha == "$expected_bundle_sha" ]] || fail trustlet_bundle_hash
[[ $(sha256sum "$stage/firmware/smplap64.b00" | cut -d' ' -f1) == 1c35ee4fcc4fad7aaadcf678ad0c7f165f013d2274027dc790bfbdf2264a5a2c ]] || fail trustlet_b00_hash
[[ $(sha256sum "$stage/firmware/smplap64.b01" | cut -d' ' -f1) == 6405fa5e69b0abe890b4fbf824295e7221c591b2ed58e13f445ef27dbdee4b44 ]] || fail trustlet_b01_hash
[[ $(sha256sum "$stage/firmware/smplap64.b02" | cut -d' ' -f1) == a483fe0af222dbc46374bdd59d8fb7b6c2a1746e37c75a3835f77c718f882783 ]] || fail trustlet_b02_hash
[[ $(sha256sum "$stage/firmware/smplap64.b03" | cut -d' ' -f1) == 80ea8e754a61dc0b81d3c3acde600372275f133fc006cdf9cbae5753bdd3d119 ]] || fail trustlet_b03_hash
[[ $(sha256sum "$stage/firmware/smplap64.b04" | cut -d' ' -f1) == ff05708a551db5c7bf0bb3c0265f4387b33fdb24e7d3f5188fa2804ddc8bd529 ]] || fail trustlet_b04_hash
[[ $(sha256sum "$stage/firmware/smplap64.b05" | cut -d' ' -f1) == e63665052e1f8fa2d5864c9970d10390d51d44e18ed822d8688643f9e3f88952 ]] || fail trustlet_b05_hash
[[ $(sha256sum "$stage/firmware/smplap64.b06" | cut -d' ' -f1) == 37e14e7466eb8aa8c1528f309a903c120e920f9f4ab61bbb145ffb15800eea2a ]] || fail trustlet_b06_hash
[[ $(sha256sum "$stage/firmware/smplap64.b07" | cut -d' ' -f1) == 80ea8e754a61dc0b81d3c3acde600372275f133fc006cdf9cbae5753bdd3d119 ]] || fail trustlet_b07_hash
[[ $(sha256sum "$stage/firmware/smplap64.b08" | cut -d' ' -f1) == 29e4ef0e39d884e24f7ed79b19479393b8c01ea6d2501c54e5b41fc31883d265 ]] || fail trustlet_b08_hash

[[ -d /sys/bus/platform/devices/qcomtee && ! -L /sys/bus/platform/devices/qcomtee/driver ]] || fail qcomtee_platform_state
! grep -qw qcomtee /proc/modules || fail module_already_loaded
! grep -qw qseecomtee /proc/modules || fail legacy_qsee_module_loaded
! pgrep -x qsee-supplicant >/dev/null || fail legacy_supplicant_running
! pgrep -x qsee-app-loader >/dev/null || fail legacy_loader_running
[[ $(find /dev -maxdepth 1 -type c \( -name 'tee[0-9]*' -o -name 'teepriv[0-9]*' \) | wc -l) -eq 0 ]] || fail preexisting_tee_nodes

dmesg_before=$(dmesg)
[[ -z $(critical_faults <<<"$dmesg_before") ]] || fail preexisting_critical_fault
[[ $(systemctl is-system-running) == running ]] || fail system_not_running
[[ $(systemctl --failed --no-legend --no-pager | sed '/^[[:space:]]*$/d' | wc -l) -eq 0 ]] || fail failed_units
baseline_dmesg_lines=$(wc -l <<<"$dmesg_before")
old_firmware_path=$(cat "$firmware_path")
[[ $old_firmware_path == "$expected_old_firmware_path" ]] || fail firmware_path_precondition
printf '%s' "$stage/firmware" >"$firmware_path"
[[ $(cat "$firmware_path") == "$stage/firmware" ]] || fail firmware_path_stage

insmod "$stage/qcomtee-control.ko" luma_control_identity=1
module_loaded=true
grep -qw qcomtee /proc/modules || fail module_did_not_load
[[ -c /dev/tee0 ]] || fail tee_node_missing
[[ -L /sys/bus/platform/devices/qcomtee/driver ]] || fail platform_driver_bind

new_dmesg=$(dmesg | tail -n "+$((baseline_dmesg_lines + 1))")
grep -Eq 'qcomtee: QTEE version [0-9]+\.[0-9]+\.[0-9]+' <<<"$new_dmesg" || fail qtee_version
grep -Fq 'luma-control: begin app=smplap64 ta_commands=0 biometric_commands=0' <<<"$new_dmesg" || fail control_begin
grep -Fq 'luma-control: privileged client environment accepted' <<<"$new_dmesg" || fail privileged_environment
grep -Fq 'luma-control: service uid=122 accepted' <<<"$new_dmesg" || fail compatibility_service
grep -Fq 'luma-control: lookup result=23 app=smplap64' <<<"$new_dmesg" || fail lookup_result
grep -Eq 'luma-control: identity accepted app=smplap64 distinguished_name=.* elf_bytes=1978456; no TA operation invoked' <<<"$new_dmesg" || fail identity_acceptance
grep -Fq 'luma-control: control TA unloaded' <<<"$new_dmesg" || fail control_unload
grep -Fq 'luma-control: complete ta_commands=0 biometric_commands=0' <<<"$new_dmesg" || fail control_complete
[[ $(grep -c 'luma-control: begin ' <<<"$new_dmesg") -eq 1 ]] || fail control_begin_count
[[ $(grep -c 'luma-control: identity accepted ' <<<"$new_dmesg") -eq 1 ]] || fail identity_count
[[ $(grep -c 'luma-control: control TA unloaded' <<<"$new_dmesg") -eq 1 ]] || fail unload_count
! grep -Eq 'luma-control: (client environment allocation failed|privileged client environment rejected|service allocation failed|service uid=.*rejected|app unexpectedly preloaded|lookup transport=|reconstruction failed=|load transport=|unload transport=)' <<<"$new_dmesg" || fail control_error
[[ -z $(critical_faults <<<"$new_dmesg") ]] || fail critical_kernel_fault
[[ $(systemctl is-system-running) == running ]] || fail system_not_running_after_probe
[[ $(systemctl --failed --no-legend --no-pager | sed '/^[[:space:]]*$/d' | wc -l) -eq 0 ]] || fail failed_units_after_probe

printf '%s\n' '--- qcomtee privileged-control-v18 evidence ---'
grep -E 'qcomtee: QTEE version|luma-control:' <<<"$new_dmesg"
printf '%s\n' '--- end qcomtee privileged-control-v18 evidence ---'

printf '%s' "$old_firmware_path" >"$firmware_path"
old_firmware_path=
rmmod qcomtee
module_loaded=false
! grep -qw qcomtee /proc/modules || fail module_did_not_unload
[[ ! -L /sys/bus/platform/devices/qcomtee/driver ]] || fail platform_did_not_unbind
[[ $(find /dev -maxdepth 1 -type c \( -name 'tee[0-9]*' -o -name 'teepriv[0-9]*' \) | wc -l) -eq 0 ]] || fail tee_nodes_remain
find "$stage" -depth -delete
[[ ! -e $stage ]] || fail stage_cleanup
cleaned=true
trap - EXIT INT TERM HUP

post_dmesg=$(dmesg | tail -n "+$((baseline_dmesg_lines + 1))")
[[ -z $(critical_faults <<<"$post_dmesg") ]] || fail cleanup_critical_fault
printf 'event=qcomtee_privileged_control_v18_complete privileged_kernel_client=true service_uid=122 control_app=smplap64 identity_accepted=true control_unloaded=true ta_commands=0 biometric_commands=0 module_loaded=false stage_present=false\n'
