[Icon Theme]
Name=Prairie
Comment=Prairie application icon theme
Inherits=Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/mimetypes,scalable/devices,symbolic/actions,symbolic/apps,symbolic/status

[scalable/apps]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/apps]
Context=Applications
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=128
MinSize=8
MaxSize=512
Type=Scalable
