# SPDX-License-Identifier: MPL-2.0
"""systemd user units for agents, and the commands they run.

Units are generated, never shipped by apps: the service writes them from a
validated declaration into $XDG_RUNTIME_DIR/systemd/user, where they vanish
with the session and are rebuilt at the next login. That is what makes the
limits the system's rather than the app's. A denied app has no background
timers; a verified first-party UI can lease its native service while open.
"""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path

from . import ids
from .categories import Category
from .declaration import MAX_ARGUMENTS, command_errors
from .desktop import FLATPAK_BINARY, DesktopEntry

HEADER = "# Generated by luma-background. Do not edit: it is rewritten at every change.\n"
NATIVE_SEARCH_PATH = ("/usr/local/bin", "/usr/bin", "/bin", "/usr/local/sbin", "/usr/sbin")
BUSCTL = "/usr/bin/busctl"
RESTART_SECONDS = 2
RESTART_STEPS = 6
RESTART_MAX_DELAY = "5min"
START_LIMIT_INTERVAL = "15min"
START_LIMIT_BURST = 8
STOP_TIMEOUT_SECONDS = 10


class CommandRefused(ValueError):
    pass


@dataclass(frozen=True, slots=True)
class AgentCommand:
    argv: tuple[str, ...]
    sandboxed: bool
    #: Whether the agent is expected to own its bus name. A portal autostart
    #: without a declaration is an ordinary program, not a kit agent.
    owns_bus_name: bool


def _executable(path: Path, *, require_system: bool) -> bool:
    try:
        info = path.stat()
    except OSError:
        return False
    if not stat.S_ISREG(info.st_mode) or not os.access(path, os.X_OK):
        return False
    if require_system:
        if not str(path.resolve()).startswith("/usr/"):
            return False
        if info.st_uid != 0 or info.st_mode & (stat.S_IWGRP | stat.S_IWOTH):
            return False
    return True


def resolve_program(program: str, *, system: bool, home: Path | None = None) -> str:
    """An absolute path for a desktop entry's program, from a fixed search path.

    The session's PATH is not consulted: it belongs to whoever set it, and an
    agent starts without anyone at the keyboard to notice a surprise.
    """

    if program.startswith("/"):
        if _executable(Path(program), require_system=system):
            return program
        raise CommandRefused(f"program is not an executable file: {program}")
    if "/" in program:
        raise CommandRefused("a relative program path is not allowed")
    search = list(NATIVE_SEARCH_PATH)
    if not system and home is not None:
        search.insert(0, str(home / ".local/bin"))
    for directory in search:
        candidate = Path(directory) / program
        if _executable(candidate, require_system=system):
            return str(candidate)
    raise CommandRefused(f"program not found: {program}")


def native_command(declared: tuple[str, ...], entry: DesktopEntry, *,
                   declaration_is_system: bool, home: Path | None = None) -> AgentCommand:
    if entry.is_flatpak:
        raise CommandRefused("a Flatpak app's agent runs in its sandbox")
    desktop_program = entry.program
    if not desktop_program:
        raise CommandRefused("the desktop entry has no Exec program")
    program = declared[0]
    trusted = declaration_is_system and entry.system
    if program == desktop_program:
        resolved = resolve_program(program, system=trusted, home=home)
    elif trusted and program.startswith("/usr/") and _executable(Path(program), require_system=True):
        # A system package may ship its agent as a separate helper. Both the
        # declaration and the helper are root-owned files under /usr, so the
        # helper is exactly as trusted as the desktop entry would have been.
        resolved = program
    else:
        raise CommandRefused(
            "background.exec must run the program named in the desktop entry's Exec"
        )
    return AgentCommand((resolved, *declared[1:]), sandboxed=False, owns_bus_name=True)


def flatpak_command(app_id: str, declared: tuple[str, ...], entry: DesktopEntry | None,
                    *, owns_bus_name: bool = True) -> AgentCommand:
    ids.app_id(app_id)
    command, arguments = declared[0], declared[1:]
    errors = command_errors(" ".join(declared))
    if errors:
        raise CommandRefused(errors[0])
    if entry is not None and entry.program and command != entry.program:
        raise CommandRefused("the agent command must be the app's own command")
    return AgentCommand(
        # --die-with-parent: stopping the unit must end the sandbox, not only
        # the bwrap process systemd knows about.
        (FLATPAK_BINARY, "run", "--die-with-parent", f"--command={command}", app_id, *arguments),
        sandboxed=True,
        owns_bus_name=owns_bus_name,
    )


def portal_autostart_command(app_id: str, exec_argv: tuple[str, ...]) -> AgentCommand:
    """Rebuild the command from a portal autostart entry, never reuse it.

    xdg-desktop-portal writes `flatpak run --command=<cmd> <app-id> <args>`
    into the person's autostart folder. That folder is writable by every
    process of the session, so the entry is only accepted when it has exactly
    that shape for exactly this app, and the command is then composed afresh.
    """

    ids.app_id(app_id)
    if len(exec_argv) < 3 or Path(exec_argv[0]).name != "flatpak" or exec_argv[1] != "run":
        raise CommandRefused("the autostart entry does not run a Flatpak")
    rest = list(exec_argv[2:])
    command = ""
    if rest and rest[0].startswith("--command="):
        command = rest.pop(0).split("=", 1)[1]
    if not rest or rest[0] != app_id:
        raise CommandRefused("the autostart entry runs a different app")
    arguments = tuple(rest[1:])
    if len(arguments) >= MAX_ARGUMENTS:
        raise CommandRefused("the autostart entry has too many arguments")
    if not command:
        errors = command_errors(" ".join(arguments)) if arguments else []
        if errors:
            raise CommandRefused(errors[0])
        return AgentCommand((FLATPAK_BINARY, "run", "--die-with-parent", app_id, *arguments), sandboxed=True,
                            owns_bus_name=False)
    return flatpak_command(app_id, (command, *arguments), None, owns_bus_name=False)


def quote_exec(argv: tuple[str, ...]) -> str:
    """ExecStart= syntax: every word quoted, specifiers and variables doubled."""

    def quote(word: str) -> str:
        if not word.isprintable():
            raise CommandRefused("command words may not contain control characters")
        escaped = word.replace("\\", "\\\\").replace('"', '\\"')
        escaped = escaped.replace("%", "%%").replace("$", "$$")
        return f'"{escaped}"'

    return " ".join(quote(word) for word in argv)


def _plain(text: str) -> str:
    """A value safe on one unit-file line, with specifiers doubled."""
    cleaned = "".join(ch for ch in text if ch.isprintable()).strip()
    return cleaned.replace("%", "%%") or "app"


@dataclass(frozen=True, slots=True)
class AgentUnitSpec:
    app_id: str
    name: str
    agent: str
    command: AgentCommand
    category: Category


def agent_service(spec: AgentUnitSpec) -> str:
    app = ids.app_id(spec.app_id)
    category = spec.category
    lines = [
        HEADER,
        "[Unit]",
        f"Description={_plain(spec.name)} background agent",
        "Documentation=https://projectluma.org/developer/kit/background-agents",
        # Agents belong to the person's session: logging out ends them, and
        # the service starts them again after the next login.
        "PartOf=graphical-session.target",
        "After=graphical-session.target luma-background.service",
        f"StartLimitIntervalSec={START_LIMIT_INTERVAL}",
        f"StartLimitBurst={START_LIMIT_BURST}",
        "",
        "[Service]",
    ]
    if spec.command.owns_bus_name and spec.agent:
        lines += ["Type=dbus", f"BusName={spec.agent}"]
    else:
        lines += ["Type=exec"]
    lines += [
        f"ExecStart={quote_exec(spec.command.argv)}",
        f"Slice={category.slice}",
        "Restart=on-failure",
        f"RestartSec={RESTART_SECONDS}s",
        f"RestartSteps={RESTART_STEPS}",
        f"RestartMaxDelaySec={RESTART_MAX_DELAY}",
        f"TimeoutStartSec=60s",
        f"TimeoutStopSec={STOP_TIMEOUT_SECONDS}s",
        f"MemoryHigh={category.memory_high}",
        f"MemoryMax={category.memory_max}",
        # Swap counts too: with zram an agent that outgrew its memory would
        # otherwise keep growing into swap instead of reaching its limit.
        f"MemorySwapMax={category.memory_high}",
        "CPUWeight=20",
        "IOWeight=20",
        # The agent runs as the person, with the app's own program. Nothing
        # here widens that; these only keep it from gaining more.
        "NoNewPrivileges=yes",
        "RestrictSUIDSGID=yes",
        "RestrictRealtime=yes",
        "LockPersonality=yes",
        "UMask=0077",
        f"Environment=LUMA_BACKGROUND_APP_ID={app}",
        f"Environment=LUMA_BACKGROUND_AGENT={spec.agent}",
        f"Environment=LUMA_BACKGROUND_CATEGORY={category.id}",
        "Environment=LUMA_BACKGROUND_MANAGED=1",
        f"SyslogIdentifier={app}",
        f"LogExtraFields=LUMA_APP_ID={app}",
        "LogExtraFields=LUMA_BACKGROUND_EVENT=agent-output",
        "",
    ]
    return "\n".join(lines)


def schedule_units(app_id: str, app_name: str, schedule: str, *, at: int = 0,
                   every: int = 0, accuracy: int = 60) -> dict[str, str]:
    """A timer and the one-line service it starts, which only asks for a wake.

    The timer does not start the agent itself: an agent that is already
    running would ignore a start, and one that is not allowed must not be
    started. It asks the service, which decides and delivers.
    """

    app = ids.app_id(app_id)
    name = ids.schedule_name(schedule)
    if bool(at) == bool(every):
        raise ValueError("a schedule has exactly one of at or every")
    timer = ids.schedule_timer(app, name)
    service = ids.schedule_service(app, name)
    accuracy = max(1, min(int(accuracy), 3600))
    timer_lines = [
        HEADER,
        "[Unit]",
        f"Description=Scheduled wake “{name}” for {_plain(app_name)}",
        "PartOf=graphical-session.target",
        "",
        "[Timer]",
        f"Unit={service}",
        f"AccuracySec={accuracy}s",
    ]
    if at:
        from datetime import datetime, timezone

        moment = datetime.fromtimestamp(int(at), tz=timezone.utc)
        timer_lines += [f"OnCalendar={moment:%Y-%m-%d %H:%M:%S} UTC", "Persistent=true"]
    else:
        every = int(every)
        if every < 300:
            raise ValueError("a repeating schedule is at least 300 seconds")
        timer_lines += [
            f"OnActiveSec={every}s",
            f"OnUnitActiveSec={every}s",
            # Spread repeating wakes so a dozen agents on the same interval do
            # not all wake the processor at the same instant.
            f"RandomizedDelaySec={min(every // 10, 300)}s",
        ]
    timer_lines.append("")
    service_lines = [
        HEADER,
        "[Unit]",
        f"Description=Deliver the “{name}” wake to {_plain(app_name)}",
        "",
        "[Service]",
        "Type=oneshot",
        "Slice=luma-background.slice",
        f"ExecStart={quote_exec((BUSCTL, '--user', '--quiet', '--timeout=90', 'call', 'org.projectluma.Background1', '/org/projectluma/Background1', 'org.projectluma.Background1', 'Wake', 'ss', app, 'schedule:' + name))}",
        "",
    ]
    return {timer: "\n".join(timer_lines), service: "\n".join(service_lines)}


def is_flatpak_scope_for(unit: str, app_id: str) -> bool:
    """The scope `flatpak run` moves itself into: app-flatpak-<app>-<n>.scope."""
    prefix = f"app-flatpak-{ids.systemd_escape(ids.app_id(app_id))}-"
    return unit.startswith(prefix) and unit.endswith(".scope") and unit[len(prefix):-6].isdigit()


MASKED = "/dev/null"


def masked_autostart(app_id: str) -> tuple[str, str]:
    """A /dev/null link that hides the session's own autostart of this app.

    Units in $XDG_RUNTIME_DIR/systemd/user take precedence over the ones
    systemd-xdg-autostart-generator writes, so the portal's autostart entry
    runs once, as the app's agent, rather than a second time outside every
    limit and switch.
    """
    return ids.autostart_unit(app_id), "/dev/null"
