# SPDX-License-Identifier: Apache-2.0
# Apple Virtualization.framework's virtio playback device must retain enough
# hardware buffering when an Android/PulseAudio client requests low latency.
# Keep the device timing independent of the graph's current quantum. The ALSA
# backend halves period-size for batch devices and clamps to device limits.
monitor.alsa.rules = [
  {
    matches = [ { alsa.driver_name = "virtio_snd" media.class = "Audio/Sink" } ]
    actions = {
      update-props = {
        api.alsa.period-size = 1024
        api.alsa.period-num = 32
        api.alsa.headroom = 4096
      }
    }
  }
]
