# SPDX-License-Identifier: Apache-2.0
# Emulator software rendering shares vCPUs with native app audio callbacks.
# Android's 5 ms requests can starve those callbacks despite a healthy ALSA
# device buffer. Apply the supported per-client minimum only to Waydroid.
pulse.rules = [
  {
    matches = [ { application.name = "Waydroid" } ]
    actions = {
      update-props = {
        pulse.min.req = 1024/48000
        pulse.min.quantum = 1024/48000
      }
    }
  }
]
