# SPDX-License-Identifier: Apache-2.0
# Luma: when a machine hangs or loses power, keep the last seconds of the
# journal instead of the last five minutes (the systemd default). Messages at
# CRIT and above are still written immediately.
[Journal]
SyncIntervalSec=15s
