#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Write the SPDX 2.3 JSON SBOM for a build (ADR-030 section 3):
# <build-dir>/sbom.spdx.json, from the image's rpm database.
#
# The generator is syft, from Anchore's published container image pinned by
# digest below (Fedora does not package syft). Every file in a Luma image is
# owned by an RPM or generated by the recipe, so the SBOM is syft's rpm
# cataloger run over the image's own rpmdb.sqlite, extracted into an otherwise
# empty directory: scanning the whole 10 GB image instead made syft index
# millions of files and exceed 30 GB of memory. The container runs without
# network access, read-only, memory-capped. If the pinned image
# cannot be obtained, the build fails rather than publishing without an SBOM;
# LUMA_OS_SBOM_FALLBACK=rpmdb selects the documented equivalent instead, an
# SPDX document generated from the image's rpm database
# (scripts/os/lib/rpmdb_spdx.py), and the provenance records which one ran.

set -euo pipefail
. "$(dirname -- "$0")/lib/common.sh"

syft_image=docker.io/anchore/syft@sha256:600896ff278677fb13b16dc35999452f4e79636fc098c9fee6ce3cffef9858e2
syft_version=1.51.1

build_dir=
case "${1:-}" in
  --build-dir) build_dir=$(realpath "${2:?}") ;;
  *) printf 'usage: %s --build-dir DIR\n' "$0" >&2; exit 2 ;;
esac
[ -d "$build_dir/oci" ] || luma_os_die "build has no OCI layout: $build_dir/oci"
out="$build_dir/sbom.spdx.json"

image_tag=$(sed -n 's/^LUMA_IMAGE_TAG=//p' "$build_dir/build.env" 2>/dev/null || true)
[ -n "$image_tag" ] || image_tag="$LUMA_OS_IMAGE_NAME:$(basename "$build_dir")"
scan="$build_dir/sbom-scan"
rm -rf "$scan"
install -d -m 0755 "$scan/usr/lib/sysimage/rpm"
luma_os_podman run --rm --net=none --security-opt label=disable "$image_tag" \
  cat /usr/lib/sysimage/rpm/rpmdb.sqlite >"$scan/usr/lib/sysimage/rpm/rpmdb.sqlite"
luma_os_podman run --rm --net=none --security-opt label=disable "$image_tag" \
  cat /usr/lib/os-release >"$scan/os-release"
install -d -m 0755 "$scan/etc" && cp "$scan/os-release" "$scan/etc/os-release"

if luma_os_podman image exists "$syft_image" || luma_os_podman pull --quiet "$syft_image" >/dev/null 2>&1; then
  luma_os_podman run --rm --net=none --security-opt label=disable \
    --memory=4g --memory-swap=4g --cpus=2 \
    --volume "$scan:/scan:ro" \
    --env SYFT_CHECK_FOR_APP_UPDATE=false \
    --env SYFT_FILE_METADATA_SELECTION=none \
    "$syft_image" scan "dir:/scan" \
    --select-catalogers rpm \
    --source-name luma-desktop --source-version "$(basename "$build_dir")" \
    --output spdx-json >"$out.partial"
  generator="syft $syft_version ($syft_image)"
elif [ "${LUMA_OS_SBOM_FALLBACK:-}" = rpmdb ]; then
  luma_os_log "syft image unavailable; generating the rpmdb SPDX equivalent"
  python3 "$luma_os_repo_root/scripts/os/lib/rpmdb_spdx.py" \
    --packages "$build_dir/packages-installed.tsv" \
    --name luma-desktop --version "$(basename "$build_dir")" >"$out.partial"
  generator="rpmdb_spdx.py (documented fallback)"
else
  luma_os_die "syft image $syft_image is unavailable and no fallback was selected"
fi

python3 - "$out.partial" <<'PY'
import json, sys
with open(sys.argv[1], encoding="utf-8") as stream:
    document = json.load(stream)
assert document.get("spdxVersion", "").startswith("SPDX-2."), "not an SPDX 2 document"
packages = document.get("packages", [])
rpms = [p for p in packages if any("pkg:rpm/" in (ref.get("referenceLocator") or "")
        for ref in p.get("externalRefs", []))]
assert len(rpms) > 500, f"SBOM lists only {len(rpms)} RPM packages"
PY
mv "$out.partial" "$out"
rm -rf "$scan"
printf '%s\n' "$generator" >"$out.generator"
luma_os_log "SBOM written by $generator"
