#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write luma-ui-tokens-private.h, the C twin of luma_appkit/lumaui_tokens.py.

The Python module is generated from config/shared/design-tokens.json; this
restates the same numbers for the C parts. `--check` fails when the header is
out of date (the C tests run it).
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "appkit" / "luma_appkit" / "lumaui_tokens.py"
TARGET = HERE / "luma-ui-tokens-private.h"


def load():
    spec = importlib.util.spec_from_file_location("lumaui_tokens", SOURCE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def name(parts):
    return "LUMA_UI_" + "_".join(str(p).upper().replace("-", "_") for p in parts)


def emit(parts, value, out):
    if isinstance(value, dict):
        for key, inner in value.items():
            emit(parts + [key], inner, out)
    elif isinstance(value, bool):
        out.append(f"#define {name(parts)} {1 if value else 0}")
    elif isinstance(value, (int, float)):
        out.append(f"#define {name(parts)} {value!r}")
    elif isinstance(value, str):
        out.append(f'#define {name(parts)} "{value}"')
    elif isinstance(value, (list, tuple)):
        if all(isinstance(v, str) for v in value):
            out.append(f"#define {name(parts)} {{ " + ", ".join(f'"{v}"' for v in value) + " }")
        else:
            for index, inner in enumerate(value):
                emit(parts + [index], inner, out)
        out.append(f"#define {name(parts + ['LEN'])} {len(value)}")


def render():
    tokens = load()
    out = ["/* SPDX-License-Identifier: Apache-2.0 */",
           "/* Generated by gen-lumaui-tokens.py from luma_appkit/lumaui_tokens.py. Do not edit. */",
           "#pragma once", ""]
    for key in sorted(k for k in vars(tokens) if k.isupper()):
        emit([key], getattr(tokens, key), out)
    roles = [role.replace("_", "-") for role in tokens.TYPE_SCALE]
    out.append("#define LUMA_UI_TYPE_ROLES { " + ", ".join(f'"{r}"' for r in roles) + ", NULL }")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"{TARGET.name} is out of date: run {Path(__file__).name}", file=sys.stderr)
            sys.exit(1)
        sys.exit(0)
    TARGET.write_text(text)
