/* Generated by scripts/developer/generate-luma-platform-tokens.py. */
#pragma once
#define LUMA_ICON_APPLICATION_CORNER_RATIO 0.25f
#define LUMA_ICON_APPLICATION_TILE_TOP_ALPHA 0.13f
#define LUMA_ICON_APPLICATION_TILE_BOTTOM_ALPHA 0.04f
#define LUMA_ICON_APPLICATION_OUTLINE_ALPHA 0.06f
