# SPDX-License-Identifier: MPL-2.0
"""luma-boot-hidden-menu: what it adds to bootupd's grub.cfg, and what it leaves alone."""
from importlib.machinery import SourceFileLoader
from importlib.util import module_from_spec, spec_from_loader
from pathlib import Path
import contextlib
import io
import os
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
HELPER = ROOT / "config/boot/luma-boot-hidden-menu"
PIECE = (ROOT / "config/boot/09_luma_hidden_menu.cfg").read_text()

loader = SourceFileLoader("luma_boot_hidden_menu", str(HELPER))
menu = module_from_spec(spec_from_loader(loader.name, loader))
loader.exec_module(menu)

PRE = """# petitboot doesn't support -e and doesn't support an empty path part
set root=$boot

if [ -f ${config_directory}/grubenv ]; then
  load_env -f ${config_directory}/grubenv
elif [ -s $prefix/grubenv ]; then
  load_env
fi

function load_video {
  insmod all_video
}

set timeout_style=menu
set timeout=1

# Other package code will be injected from here
"""
PIECES = {
    "01_users.cfg": "# Keep the comment for grub2-set-password\nif [ -f ${prefix}/user.cfg ]; then\n  source ${prefix}/user.cfg\nfi\n",
    "08_greenboot.cfg": "insmod increment\nset boot_success=0\nsave_env boot_success\n",
    "10_blscfg.cfg": "blscfg\n",
    "14_menu_show_once.cfg": 'if [ "${menu_show_once_timeout}" ]; then\n  set timeout_style=menu\n  set timeout="${menu_show_once_timeout}"\nfi\n',
    "30_uefi-firmware.cfg": "if [ \"$grub_platform\" = \"efi\" ]; then\n  menuentry 'UEFI Firmware Settings' {\n    fwsetup\n  }\nfi\n",
    "41_custom.cfg": "if [ -f $prefix/custom.cfg ]; then\n  source $prefix/custom.cfg\nfi\n",
}


def bootupd(pieces, pre=PRE):
    """Exactly what bootupd 0.2.35's grubconfigs::install writes."""
    config = "# Generated by bootupd / do not edit\n\n" + pre
    for name in sorted(pieces):
        config += f"\n### BEGIN {name} ###\n" + pieces[name] + f"### END {name} ###\n"
    return config


class HiddenMenu(unittest.TestCase):
    def setUp(self):
        self.dir = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.dir)
        self.cfg = self.dir / "grub.cfg"
        self.source = self.dir / "09_luma_hidden_menu.cfg"
        self.source.write_text(PIECE)

    def run_helper(self, *extra, text=None):
        if text is not None:
            self.cfg.write_text(text)
            os.chmod(self.cfg, 0o600)
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            code = menu.main(["--grub-cfg", str(self.cfg), "--source", str(self.source), *extra])
        return code, out.getvalue()

    def test_updated_computer_gets_exactly_what_a_fresh_install_gets(self):
        code, out = self.run_helper(text=bootupd(PIECES))
        self.assertEqual(code, 0)
        self.assertIn("added the hidden-menu piece", out)
        self.assertEqual(self.cfg.read_text(), bootupd({**PIECES, "09_luma_hidden_menu.cfg": PIECE}))
        self.assertEqual(os.stat(self.cfg).st_mode & 0o777, 0o600)
        self.assertEqual((self.dir / "grub.cfg.pre-luma-hidden-menu").read_text(), bootupd(PIECES))

    def test_idempotent(self):
        self.run_helper(text=bootupd(PIECES))
        first = self.cfg.read_text()
        code, out = self.run_helper()
        self.assertEqual((code, self.cfg.read_text()), (0, first))
        self.assertIn("is current", out)

    def test_remove_is_the_exact_inverse(self):
        for pieces in (PIECES, {k: v for k, v in PIECES.items() if k < "09"}):
            original = bootupd(pieces)
            self.run_helper(text=original)
            self.assertNotEqual(self.cfg.read_text(), original)
            code, out = self.run_helper("--remove")
            self.assertEqual((code, self.cfg.read_text()), (0, original), out)

    def test_refreshes_a_changed_piece_body_only(self):
        self.run_helper(text=bootupd({**PIECES, "09_luma_hidden_menu.cfg": "set timeout_style=hidden\nset timeout=3\n"}))
        self.assertEqual(self.cfg.read_text(), bootupd({**PIECES, "09_luma_hidden_menu.cfg": PIECE}))

    def test_replaces_the_first_name_from_install_and_from_migration(self):
        legacy = bootupd({**PIECES, "13_luma_hidden_menu.cfg": PIECE})
        self.run_helper(text=legacy)
        self.assertEqual(self.cfg.read_text(), bootupd({**PIECES, "09_luma_hidden_menu.cfg": PIECE}))
        # migrate-to-channel.sh (1.luma.14) put it inside 10_blscfg, before the BLS line.
        migrated = bootupd({**PIECES, "10_blscfg.cfg": "### BEGIN 13_luma_hidden_menu.cfg ###\n" + PIECE +
                            "### END 13_luma_hidden_menu.cfg ###\nblscfg\n"})
        self.run_helper(text=migrated)
        self.assertEqual(self.cfg.read_text(), bootupd({**PIECES, "09_luma_hidden_menu.cfg": PIECE}))

    def test_comes_before_the_luma_advanced_surface(self):
        policy = bootupd({**PIECES, "10_blscfg.cfg": "source $prefix/luma.cfg\n"})
        self.run_helper(text=policy)
        text = self.cfg.read_text()
        self.assertLess(text.index("set timeout_style=hidden"), text.index("source $prefix/luma.cfg"))
        self.assertLess(text.index("set timeout_style=hidden"), text.index("### BEGIN 14_menu_show_once.cfg ###"))

    def assert_left_alone(self, text, reason):
        code, out = self.run_helper(text=text)
        self.assertEqual((code, self.cfg.read_text()), (0, text))
        self.assertIn(reason, out)
        self.assertFalse((self.dir / "grub.cfg.pre-luma-hidden-menu").exists())

    def test_leaves_administrators_menu_timing_alone(self):
        self.assert_left_alone(bootupd(PIECES, PRE.replace("timeout_style=menu\nset timeout=1",
                                                            "timeout_style=hidden\nset timeout=0")),
                               "preamble's menu timeout is not bootupd's")
        self.assert_left_alone(bootupd(PIECES, PRE.replace("set timeout=1", "set timeout=5")),
                               "preamble's menu timeout is not bootupd's")
        self.assert_left_alone(bootupd({**PIECES, "50_mine.cfg": "set timeout=10\n"}),
                               "outside the pieces that own one")
        (self.dir / "custom.cfg").write_text("set timeout_style=countdown\n")
        self.assert_left_alone(bootupd(PIECES), "custom.cfg sets a menu timeout")

    def test_leaves_other_bootloader_configurations_alone(self):
        self.assert_left_alone("### BEGIN /etc/grub.d/00_header ###\nset timeout=5\n", "not generated by bootupd")
        (self.dir / "custom.cfg").write_text("menuentry 'Mine' { true }\n")
        code, out = self.run_helper(text=bootupd(PIECES))
        self.assertIn("added", out)

    def test_missing_piece_or_file_changes_nothing(self):
        self.source.unlink()
        self.assert_left_alone(bootupd(PIECES), "is not installed")
        self.cfg.unlink()
        code, out = self.run_helper()
        self.assertEqual(code, 0)
        self.assertIn("does not exist", out)
        self.assertFalse(self.cfg.exists())

    def test_dry_run(self):
        code, out = self.run_helper("--dry-run", text=bootupd(PIECES))
        self.assertEqual((code, self.cfg.read_text()), (0, bootupd(PIECES)))
        self.assertIn("would have added", out)

    @unittest.skipUnless(shutil.which("grub2-script-check"), "grub2-script-check is not installed")
    def test_result_passes_grub2_script_check(self):
        self.run_helper(text=bootupd(PIECES))
        subprocess.run(["grub2-script-check", str(self.cfg)], check=True)


if __name__ == "__main__":
    unittest.main()
