# SPDX-License-Identifier: Apache-2.0
# Best-effort protection for the compositor's resident working set. This is
# neither allocated memory nor a hard reservation, and does not page in swap.
# The image's uresourced configuration supplies the active-user ancestors and
# session.slice budget; uresourced caps the whole user.slice budget to 10% RAM.
# A leaf-only allocation is ineffective when an ancestor has no protection.
[Service]
MemoryLow=1G
